### ISSUE TITLE
Returns weight information (axis or full matrix) after averaging operation

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#114]
### Is your feature request related to a problem? If yes, Please describe

Weights are not returned in the Dataset after spatial averaging.

### Describe your proposed solution

Attached the weights in the Dataset as the `var_wts` (e.g., `tas_wits`) after spatially averaging.

### Describe alternatives solutions you've considered

N/A

### Additional context

N/A

**Comment by taylor13** [comment]
If I understand it correctly, I think this is a good idea.  The weights might be needed for subsequent operations.

**Comment by durack1** [comment]
@tomvothecoder if this will be implemented through `xESMF` then there may be some other outputs that could also be grabbed, if I recall correctly, if `diags = {}` was defined as an empty dictionary and passed to the ESMPy call many diagnostics generated through the regridding process were returned, with the weights being one of numerous outputs (this is as close as I can find regarding docs for this in cdms2 https://cdms.readthedocs.io/en/latest/regrid2.html#regrid2.mvESMFRegrid.ESMFRegrid.fillInDiagnosticData)

**Comment by pochedls** [comment]
@durack1 - we don't use xESMF for spatial averaging. 

I think this issue can probably be closed since the weights can be retrieved via `.get_weights()` [here](https://github.com/xCDAT/xcdat/blob/main/xcdat/spatial.py#L297). If a more complex implementation of this is needed in the future, that could probably be added as a feature request.

**Comment by durack1** [comment]
@pochedls interesting, how consistent are the xESMF weights and the weights being generated through the separate spatial averaging routine?

**Comment by pochedls** [comment]
> @pochedls interesting, how consistent are the xESMF weights and the weights being generated through the separate spatial averaging routine?

I have never used ESMF for spatial averaging – so I haven't attempted to compare the weights.

**Comment by tomvothecoder** [comment]
> @durack1 - we don't use xESMF for spatial averaging.
> 
> I think this issue can probably be closed since the weights can be retrieved via .get_weights() [here](https://github.com/xCDAT/xcdat/blob/main/xcdat/spatial.py#L297). If a more complex implementation of this is needed in the future, that could probably be added as a feature request.

I had an inclination that the `._get_weights()` methods would be useful for users. I added a related issue to make those methods public (https://github.com/xCDAT/xcdat/issues/251).

Closing this based on the discussion.
