### ISSUE TITLE
Add `xcdat.open()` to wrap `xcdat.open_dataset()` and `xcdat.open_mfdataset()`

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#128]
### Is your feature request related to a problem? If yes, Please describe

Suggesting a thin wrapper for opening files. Because cdscan-generated xml is still a major part of the PCMDI’s CMIP database, having the capability of open xmls in addition would help buying some time when transitioning PMP to use xcdat. 

### Describe your proposed solution

xcdat.open(input)
If input is string and .nc file, use xcdat.open_dataset
If input is list of .nc files, use xcdat.open_mfdataset
If input is string and .xml file, read xml (which is ascii file) and find where linked .nc files are, and depending if linked data file is single .nc file or multiple .nc files, use xcdat_opendataset or xcdat.open_mfdataset

### Additional context

@pochedls's comment:
"To query for CMIP paths, you need to import xrw (here) and call xrw.get_cmip_paths(). Alternatively, I think you could open an xml file following something like [this](https://gist.github.com/pochedls/5c331279f65e0383bfb506cc33e60c87). This is all “scratch” code…"

**Comment by durack1** [comment]
@tomvothecoder @lee1043 happy to be an ocean guinea pig for this, so large (multi 10GB) files
