### ISSUE TITLE
Update doc vars

### ISSUE THREAD

**Issue by lee1043** [XCDAT/xcdat#130]
### Describe your documentation update

In this [example](https://xcdat.readthedocs.io/en/latest/generated/xcdat.spatial_avg.html#module-xcdat.spatial_avg) for the spatial average, variable `tas` is used for deriving [Nino 3.4 index]((https://www.ncdc.noaa.gov/teleconnections/enso/indicators/sst/)). However in CMIP, the variable name `tas` has been indicating near surface (2-m) temperature, I think it would make more sense to use `ts` variable instead, which is for surface temperature (thus considered as sea-surface temperature over ocean). 

I suggest replacing `tas` by `ts`.

**Comment by tomvothecoder** [comment]
Another doc caught in https://github.com/XCDAT/xcdat_test/pull/27 to be done with this issue:
`data_var` should replace `keep_var`
