### ISSUE TITLE
Add option to specify longitude axis system when opening up a dataset

### ISSUE THREAD

**Issue by tomvothecoder** [XCDAT/xcdat#135]

**Comment by chengzhuzhang** [comment]
Yeah, I noticed this in my testing too (See line 12 in https://github.com/XCDAT/xcdat_test/blob/demo_e3sm/validation/general_utils/Test_general_utils.ipynb. )., to reconcile longitude axis system will be a huge plus.

**Comment by tomvothecoder** [comment]
> ...are there cases where dataset files might use the two different longitude axes orientations (180 or 360) and we need to reconcile them to a single orientation before concatenating them into a single Dataset?

From the meeting: files are usually from a single model run so the axis orientation should be the same across files. Joining files from different runs isn't a common practice.

We don't need to preprocess each individual file, just call `swap_lon_axes()` after `xr.open_mfdataset()`.

**Comment by chengzhuzhang** [comment]
@pochedls I'm also curious how cdms is handling longitude systems. would you point to the codes?

**Comment by pochedls** [comment]
I'm not sure of where the code is, but here is the behavior I was referring to yesterday (where the longitude bounds that span the prime meridian are repeated in different "units"):

```
fn = '/p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/tas/CMIP6.CMIP.historical.CSIRO.ACCESS-ESM1-5.r10i1p1f1.mon.tas.atmos.glb-z1-gn.v20200605.0000000.0.xml'
f = cdms2.open(fn)
tas_orig = f('tas', time=slice(0, 1))
lon_orig = tas_orig.getLongitude()
tas_reorder = f('tas', time=slice(0, 1), longitude=(0, 360))
lon_reorder = tas_reorder.getLongitude()
f.close()
print('Original lon size ' + str(len(lon_orig)))
print('Original first and last longitude value: ', lon_orig[0], lon_orig[-1])
print('Original first and last longitude bounds: ', lon_orig.getBounds()[0], lon_orig.getBounds()[-1])

print()
print('Reordered lon size ' + str(len(lon_reorder)))
print('Reordered first and last longitude value: ', lon_reorder[0], lon_reorder[-1])
print('Reordered first and last longitude bounds: ', lon_reorder.getBounds()[0], lon_reorder.getBounds()[-1])
```

> Original lon size 192                                                                                                                           
> Original first and last longitude value:  0.0 358.125
> Original first and last longitude bounds:  [-0.9375  0.9375] [357.1875 359.0625]
> 
> Reordered lon size 193
> Reordered first and last longitude value:  0.0 360.0
> Reordered first and last longitude bounds:  [-0.9375  0.9375] [359.0625 360.9375]
