### ISSUE TITLE
KeyError in spatial_average when open multiple datasets

### ISSUE THREAD

**Issue by chengzhuzhang** [XCDAT/xcdat#136]
### What versions of software are you using?

-   Package Version: 0.1.0

### What are the steps to reproduce this issue?

Please refer to https://github.com/XCDAT/xcdat_test/blob/demo_e3sm/validation/general_utils/Test_general_utils.ipynb
From line 164. 
If only one dataset is supplied, no error. But if use wildcard '*' to open multiple variables, it returns error messages as below.

To preproduce:
1. get one year of data from here /p/user_pub/PCMDIobs/PCMDIobs2/atmos/3hr/pr/TRMM-3B43v-7/gn/v20200707 (note the difference file name)
2. And follow the Jupyter Notebook steps from Line 13 .

### What happens? Any logs, error output, etc?

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/var/folders/v5/66rvtx3s2ld04xj_pz7cgtd4001nnm/T/ipykernel_92384/1036211618.py in <module>
----> 1 pr_global = ds2.xcdat.spatial_avg(axis=["lat", "lon"]).pr

~/miniconda3/envs/xcdat_test/lib/python3.9/site-packages/xcdat/xcdat.py in spatial_avg(self, data_var, axis, weights, lat_bounds, lon_bounds)
     43     ) -> xr.Dataset:
     44         obj = DatasetSpatialAverageAccessor(self._dataset)
---> 45         return obj.avg(data_var, axis, weights, lat_bounds, lon_bounds)
     46 
     47     @property  # type: ignore

~/miniconda3/envs/xcdat_test/lib/python3.9/site-packages/xcdat/spatial_avg.py in avg(self, data_var, axis, weights, lat_bounds, lon_bounds)
    147             weights = self._get_weights(axis, lat_bounds, lon_bounds)
    148 
--> 149         self._validate_weights(da_data_var, axis, weights)
    150         dataset[da_data_var.name] = self._averager(da_data_var, axis, weights)
    151         return dataset

~/miniconda3/envs/xcdat_test/lib/python3.9/site-packages/xcdat/spatial_avg.py in _validate_weights(self, data_var, axis, weights)
    616 
    617         if "lat" in axis and lat_key not in weights.dims:
--> 618             raise KeyError(f"Check weights DataArray includes {lat_key} dimension.")
    619 
    620         if "lon" in axis and lon_key not in weights.dims:

KeyError: 'Check weights DataArray includes lat dimension.'

**Comment by pochedls** [comment]
@tomvothecoder / @chengzhuzhang  - Okay - I do see this issue. Could we add `data_vars="minimum"` in `xcdat.open_mfdataset()`? Or detect when it needs to be included?

**Comment by tomvothecoder** [comment]
- @tomvothecoder / @chengzhuzhang - Okay - I do see this issue. Could we add data_vars="minimum" in xcdat.open_mfdataset()? Or detect when it needs to be included?

Yup, I've added `data_vars="minimum"` as the default value in `xcdat.open_mfdataset()`. Here's the file in the related PR:
https://github.com/XCDAT/xcdat/pull/143/files#diff-e5b713e4bf50c61361496f77fdadcf9d3ffc2fcb39c4c953932cd780ae951e55
