### ISSUE TITLE
Cannot generate bounds for a dataset that has no bounds

### ISSUE THREAD

**Issue by chengzhuzhang** [XCDAT/xcdat#137]
### What versions of software are you using?

-   Package Version: v0.1.0

### What are the steps to reproduce this issue?

1.  get data from here: https://web.lcrc.anl.gov/public/e3sm/diagnostics/observations/Atm/climatology/SSMI/SSMI_ANN_climo.nc

2. ds = xcdat.open_dataset(test_file, data_var = 'PRECT_OCEAN')

### What happens? Any logs, error output, etc?

ds3 = xcdat.open_dataset(demo_file3, data_var = 'PRECT_OCEAN')
https://ghostbin.com/18GU3

### What were you expecting to happen?

The open_dataset function directly from xarray seems working properly.
ds = xarray.open_dataset(demo_file3)

cdms.open also works.

**Comment by tomvothecoder** [comment]
I opened up the Dataset and noticed there is only a single coordinate point for time:
```
ds = xr.open_dataset("./input/SSMI_ANN_climo.nc")

ds.time
<xarray.DataArray 'time' (time: 1)>
array([83.5], dtype=float32)
Coordinates:
  * time     (time) float32 83.5
Attributes:
    units:    Base day plus integration time
```

`xcdat.bounds.add_bounds()` requires coordinates to be a length >1. The diffs between each point is used to calculate each of their lower and upper bounds, which isn't possible if there is only 1 coordinate point. The logic and validation steps for this method is based on [`iris.coord.AuxCoord.guess_bounds()`](https://github.com/SciTools/iris/blob/2202793568ca1eb23f1f8e9be42afae0f1383f34/lib/iris/coords.py#L2043-L2046).

Refer to the function below for more info:
https://github.com/XCDAT/xcdat/blob/d73d910fca373f52dc45c13f636e84482079035d/xcdat/bounds.py#L182-L258

Assuming that a single time coordinate point is expected and we don't need to generate time bounds, maybe we can catch the exception for `xcdat.bounds.fill_missing()` and produce a warning instead? Also, I'll update the error message so it is clearer which axes it is referring to.

**Comment by chengzhuzhang** [comment]
Hey Tom, I think we should tolerate data with coordinates that only have one point, and yes it makes sense not to generate bounds for these coordinates. Catch this exception in fill_missing() sounds good to me. May be we can consider to rename `fill_missing` to `fill_missing_bounds` to be more explicit? Fill_missing often specifically means fill missing values.
