### ISSUE TITLE
Specifying conda-forge during installation

### ISSUE THREAD

**Issue by jypeter** [XCDAT/xcdat#160]
You may want to explicitly specify the conda-forge channel in the [Stable release](https://xcdat.readthedocs.io/en/latest/getting_started.html#stable-release) installation, i.e. `conda install -c conda-forge xcdat`

This is obvious for most users, but always keep in mind that things should be made extra-easy for new users

**Comment by tomvothecoder** [comment]
Thanks for the suggestion @jypeter!
