### ISSUE TITLE
conflicting values for variable 'lat_bnds'

### ISSUE THREAD

**Issue by pochedls** [XCDAT/xcdat#162]
### What versions of software are you using?

-   Package Version: Main branch / Release 0.1.0

### What are the steps to reproduce this issue?
```
import xcdat

p = '/p/css03/scratch/cmip6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Amon/tas/gn/v20190914/*nc'
ds = xcdat.open_mfdataset(p)
```

> MergeError: conflicting values for variable 'lat_bnds' on objects to be combined. You can skip this check by specifying compat='override'.

### What happens? Any logs, error output, etc?

I think this is happening because the `lat_bnd` values have slight (e.g., 10<sup>-13</sup>) differences in the different netCDF files.

### Any other comments?
Opening with xarray works fine (as long as you do not set `data_vars="minimal"`), though the `lat_bnd` is larger than expected:

```
import xarray as xr
ds = xr.open_mfdataset(p)
print(ds.lat_bnds.shape)
```
> (2160, 142, 2)

It appears that the bounds differ depending on timestep:
```
np.array(ds.lat_bnds[0] - ds.lat_bnds[-1])
```

> array([[-9.00000000e+01, -8.90526316e+01],
>           [-8.90526316e+01, -8.71578947e+01],
>        [-8.71578947e+01, -8.52631579e+01],
> ...
>        [            nan,             nan],
>        [ 8.90526316e+01,  9.00000000e+01],
>        [            nan,             nan]])

I'm not totally sure why there are `NaN` values. They don't appear when I use `ncdump -v lat_bnds /p/css03/scratch/cmip6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Amon/tas/gn/v20190914/tas_Amon_NorCPM1_historical_r10i1p1f1_gn_185001-201412.nc`, but they do appear after loading the dataset with xarray. 

I do not know what to do with this problem, though CDAT seems to be able to load the bounds with no problem.

**Comment by tomvothecoder** [comment]
> Opening with xarray works fine (as long as you do not set data_vars="minimal"), though the lat_bnd is larger than expected:

> ```
> import xarray as xr
> ds = xr.open_mfdataset(p)
> print(ds.lat_bnds.shape)
> (2160, 142, 2)
> ```

The time dimension gets concatenated to non-time variables like lat_bnds (shown below) when `data_vars="minimal"` is not set. Related open issue with concatenation of dims: https://github.com/pydata/xarray/issues/2064
```
>>> ds.lat_bnds.dims
('time', 'lat', 'bnds')
```


The [possible solution](https://github.com/pydata/xarray/issues/2064#issuecomment-531818131
), in addition to `data_vars="minimal"`, includes `coords="minimal"` and `compat="override"`.

- `data_vars`: These data variables will be concatenated together:
  - “minimal”: Only data variables in which the dimension already appears are included.
- `coords`: These coordinate variables will be concatenated together:
  -  “minimal”: Only coordinates in which the dimension already appears are included.
- `compat`: String indicating how to compare variables of the same name for potential conflicts when merging
  - “override”: skip comparing and pick variable from first dataset


```python
#%%
import xarray as xr

import xcdat

#%%
p = "/p/css03/scratch/cmip6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Amon/tas/gn/v20190914/*nc"

#%%
# xarray without data_vars="minimal" (concats time dimension)
>>> ds_xr_no_min = xr.open_mfdataset(p)
>>> ds.xr_no_min.lat_bnds.shape
(2160, 142, 2)

# xcdat with only data_vars="minimal" (conflicting error)
>>> ds_xcdat_no_min = xcdat.open_mfdataset(p)
MergeError: conflicting values for variable 'lat_bnds' on objects to be combined. You can skip this check by specifying compat='override'.

#%%
# xarray with all correct settings
>>> ds_xr_with_min = xr.open_mfdataset(
    p, data_vars="minimal", coords="minimal", compat="override"
)
>>> ds_xr_with_min.lat_bnds.shape
(142, 2)

# xcdat with all correct settings
>>> ds_xcdat_with_min = xcdat.open_mfdataset(p, coords="minimal", compat="override")
>>> ds_xcdat_with_min.lat_bnds.shape
(142, 2)
```

> It appears that the bounds differ depending on timestep:
> ```
> np.array(ds.lat_bnds[0] - ds.lat_bnds[-1])
> ```
> 
> > array([[-9.00000000e+01, -8.90526316e+01],
> >           [-8.90526316e+01, -8.71578947e+01],
> >        [-8.71578947e+01, -8.52631579e+01],
> > ...
> >        [            nan,             nan],
> >        [ 8.90526316e+01,  9.00000000e+01],
> >        [            nan,             nan]])
> 
> I'm not totally sure why there are `NaN` values. They don't appear when I use `ncdump -v lat_bnds /p/css03/scratch/cmip6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Amon/tas/gn/v20190914/tas_Amon_NorCPM1_historical_r10i1p1f1_gn_185001-201412.nc`, but they do appear after loading the dataset with xarray. 
> 

After resolving the concatenation of the time dimension and data variable compatibility issues, I still noticed `NaN` values as well. I am investigating why this is happening in xarray.

```
>>>ds_xr_with_min.lat_bnds[0].values
array([-90.        , -89.05263158])

>>> ds_xr_with_min.lat_bnds[-1].values
array([nan, nan])
```

**Comment by tomvothecoder** [comment]
I think nan values are being produced because there are very small differences in lat_bnds values as you mentioned (also shown in code example below) and an **outer join (union of object indexes)** is performed by default. These nan values subsequently increase the size of lat_bnds from (96, 2) to (142, 2) after calling `open_mfdataset()`.

Comparing shapes of lat_bnds between datasets and performing floating point comparison:
```
p1 = f"{path}tas_Amon_NorCPM1_historical_r10i1p1f1_gn_185001-201412.nc"
p2 = f"{path}tas_Amon_NorCPM1_historical_r10i1p1f1_gn_201501-201812.nc"
p3 = f"{path}tas_Amon_NorCPM1_historical_r10i1p1f1_gn_201901-202912.nc"

>>> ds1 = xr.open_dataset(p1)
>>> ds2 = xr.open_dataset(p2)
>>> ds3 = xr.open_dataset(p3)
>>> ds1.lat_bnds.shape
(96, 2)
>>> ds2.lat_bnds.shape
(96, 2)
>>> ds3.lat_bnds.shape
(96, 2)

>>> np.testing.assert_allclose(ds1.lat_bnds, ds2.lat_bnds)
>>> np.testing.assert_allclose(ds1.lat_bnds, ds3.lat_bnds)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 192 (1.04%)
Max absolute difference: 0.
Max relative difference: 0.
 x: array([[-90.      , -89.052632],
       [-89.052632, -87.157895],
       [-87.157895, -85.263158],...
 y: array([[-90.      , -89.052632],
       [-89.052632, -87.157895],
       [-87.157895, -85.263158],...


>>>np.testing.assert_allclose(ds2.lat_bnds, ds3.lat_bnds)
True
```

Comparing difference joins since I noticed that the lat_bnds of the individual datasets had a shape of (96, 2), not (142, 2):
```
# “outer”: use the union of object indexes (default xarray value)
# ==========================================================
>>> ds = xcdat.open_mfdataset(
    p, data_vars="minimal", coords="minimal", compat="override", join="outer"
)
>>> ds.lat_bnds.shape
(142, 2)
>>> ds_left.lat_bnds.isnull().values
Has null values

# "left": use indexes from the first object with each dimension
# ==========================================================
>>> ds_left = xcdat.open_mfdataset(
    p, data_vars="minimal", coords="minimal", compat="override", join="left"
)
>>> ds_left.lat_bnds.shape
(96, 2)
>>> ds_left.lat_bnds.isnull().values
No null values

# “override”: if indexes are of same size, rewrite indexes to be those of the first object with that dimension. Indexes for the same dimension must have the same size in all objects.
# ==========================================================
>>> ds_override = xcdat.open_mfdataset(
    p, data_vars="minimal", coords="minimal", compat="override", join="override"
)
>>> ds_left.lat_bnds.shape
(96, 2)
>>> ds_override.lat_bnds.isnull().values
No null values

# %%
>>> ds_left.lat_bnds.identical(ds_override.lat_bnds)
True
```

The possible solutions I found so far are to use `join="left"` or `join="override"` in `open_mfdataset()`, but there may be implications with this option (e.g., if the first dataset has missing values and you use them for the single joined dataset).

**Comment by tomvothecoder** [comment]
Based on my findings above, I think we should provide those two options in the docs/docstring for cases where Datasets have conflicting values.

Since xarray/xcdat provides kwarg args to handle this edge case, we should probably avoid implementing code to try to handle it.

**Comment by pochedls** [comment]
This seems like a reasonable solution. One slightly more complex way of handling this situation would be to try to detect this problem with a pre-processor function, which could throw a warning or exception. I wasn't sure if the pre-processor functions can communicate information between files (e.g., to compare bounds across files) or if they must act independently on each netcdf file (and thus cannot compare bounds *across* files).
