### ISSUE TITLE
Investigate CDAT versus xcdat spatial average differences

### ISSUE THREAD

**Issue by pochedls** [XCDAT/xcdat#166]
In order to continue to validate the spatial averaging code in `xcdat`, I looped over CMIP5/6 tas historical files (110 models) and 20+ domains [here](https://github.com/PCMDI/pcmdi_metrics/blob/27903488adefe1a2941100dfb56dceceb0321310/share/default_regions.py). 

227 (227/2486 = 9%) combinations had a CDAT-xcdat difference larger than 10<sup>-6</sup> [here](https://ghostbin.com/Ft18H/raw). 110 were specific to the NAFM region. This drops to 140 (and 110 for NAFM) if I look at differences larger than 10<sup>-3<sup>.

Two models produced errors for xcdat (but not CDAT): NorCPM1 and MCM-UA-1-0. In the case of NorCPM, it is related to Issue #162. In the case of MCM-UA-1-0, the problem is likely related to #163. There were no cases where CDAT throws an error and xcdat does not. Both packages produce an error for ICON-ESM-LR, because tas has a shape of [1980, 20480] (non-rectilinear grid).

This ticket is intended to document my findings in investigating these differences.

**Comment by pochedls** [comment]
@lee1043 - In the metrics package for NAFM - do you load data differently when computing metrics for NAFM (e.g., tas = f('tas', longitude=(310, 309)) or something like this)? The longitude domain goes from 310<sup>o</sup>E to 60<sup>o</sup>E (wraps around the prime meridian). I suspect when I am calling CDAT it is averaging between 60<sup>o</sup>E and 310<sup>o</sup>E (rather than wrapping around the prime meridian.

**Comment by lee1043** [comment]
@pochedls I think you've just found a bug in the PMP's Monsoon Wang metric's domain definition. I haven't had a chance to work with this specific metric so was not noticing the issue. In the PMP's driver for the Monsoon Wang metric, it just opens model file with regular cdms2 open, as [`f = cdms2.open(modelFile)`](https://github.com/PCMDI/pcmdi_metrics/blob/9d036a6b48296e27e08636cb918799f6fbe0cf06/pcmdi_metrics/monsoon_wang/monsoon_wang_driver.py#L189)

As you suspected, the extracted subdomain for NAFM (North African Monsoon) was for 60E to 310E with mirrored, instead of 310E to 60E. 

![NAFM](https://user-images.githubusercontent.com/17091564/142713965-f42f1ec6-e024-43ba-99b1-6b21f2670a66.png)

I am bringing this issue to [PMP issue](https://github.com/PCMDI/pcmdi_metrics/issues/820) for fix. On the other hand, although it is not expected but I think it would be nice if XCDAT handles this smartly if there is an easy way to do so.

**Comment by pochedls** [comment]
> I am bringing this issue to PMP issue for fix. On the other hand, although it is not expected but I think it would be nice if XCDAT handles this smartly if there is an easy way to do so.

I've tried to ensure that `xcdat` handles situations where the bounds cross the prime meridian. You need to specify the bounds as `(lower, upper)`. If you specify a bound of `(310, 60)`, it knows that you are wrapping around the prime meridian (i.e., 310 - 360 and 0 - 60) where as `(60, 310)` would not span the prime meridian (it includes only 60 - 310).

**Comment by tomvothecoder** [comment]
Hi @pochedls, any progress on this issue?

**Comment by pochedls** [comment]
> Hi @pochedls, any progress on this issue?

Thank you for the prompt - I haven't dug deeper, but I will devote some time to this along with the two other PR reviews. It looks like the majority of the differences are not xcdat bugs, but some of the differences I do not yet understand.

**Comment by pochedls** [comment]
I found the source of another difference in spatial averages: the latitude bounds. To summarize what I show below, the latitude bounds by xcdat match the `lat_bnds` array in the original file. If I drop the xcdat bounds (`ds.drop_vars(['lat_bnds'])`) and regenerate them (`ds = ds.bounds.add_missing_bounds()`) I match the bounds in CDAT.

```
fn = '/p/user_pub/xclim/CMIP5/CMIP/historical/atmos/mon/tas/CMIP5.CMIP.historical.BNU.BNU-ESM.r1i1p1.mon.tas.atmos.glb-z1-gu.1.0000000.0.xml'
f = cdms2.open(fn)
tas = f('tas', time=slice(0, 1))
f.close()
lat_bnds = tas.getLatitude().getBounds()
print(lat_bnds)
```

> array([[-89.24743652, -86.48016358],
>        [-86.48016358, -83.70471955],
>        [-83.70471955, -80.91925812],
>        [-80.91925812, -78.13125229],
>        [-78.13125229, -75.34220887],
>        [-75.34220887, -72.55263519],
> ...

```
fn = '/p/css03/cmip5_css02/data/cmip5/output1/BNU/BNU-ESM/historical/mon/atmos/Amon/r1i1p1/tas/1/tas_Amon_BNU-ESM_historical_r1i1p1_185001-200512.nc'
ds = xcdat.open_dataset(fn)
lat_bnds = ds.bounds.get_bounds('lat')
ds.close()
print(lat_bnds)
```

> array([[-87.8638  , -86.480164],
>        [-86.480164, -83.70472 ],
>        [-83.70472 , -80.919258],
>        [-80.919258, -78.131256],
>        [-78.131256, -75.342209],
>        [-75.342209, -72.552635],
> ...

We can compare to the bounds in the original file via `ncdump -v lat_bnds tas_Amon_BNU-ESM_historical_r1i1p1_185001-200512.nc`

>  lat_bnds =
>   -87.8638000488281, -86.4801635742188,
>   -86.4801635742188, -83.704719543457,
>   -83.704719543457, -80.9192581176758,
>   -80.9192581176758, -78.1312561035156,
>   -78.1312561035156, -75.3422088623047,
>   -75.3422088623047, -72.5526351928711,
> ...

All of the methods agree on the `lat` values themselves:

>  lat = -87.8638000488281, -85.0965270996094, -82.3129119873047,
>     -79.5256042480469, -76.7369003295898, -73.9475173950195,
>     -71.1577529907227, -68.3677597045898, -65.5776062011719,
>     -62.787353515625, -59.9970207214355, -57.2066307067871,
>     -54.4161987304688, -51.625732421875, -48.8352394104004,
> ...

If I drop the xcdat bounds (`ds.drop_vars(['lat_bnds'])`) and regenerate them (`ds = ds.bounds.add_missing_bounds()`) I match the bounds in CDAT.

Of the most recent 2373 xcdat-CDAT comparisons, there were 117 instances where the two libraries had a spatial average differences greater than 10<sup>-6</sup> (for an individual time step). Some of these cases were larger than 10<sup>-3</sup> (including the file outlined above). By generating the latitude bounds in xcdat instead of using the bounds in the file, 33 (of 117) differences become smaller than 10<sup>-6</sup>. This leaves 84 comparisons where the differences are still larger than 10<sup>-6</sup>.

Can anyone see a reason not to use the latitude bounds in the file?

**Comment by pochedls** [comment]
It appears that some of the differences may be in the averager (or maybe the precision of the underlying data?).

## get spatial averages
```
import xcdat
import cdms2
import cdutil
import numpy as np

fn = '/p/css03/esgf_publish/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA/historical/r1i1p1f1/Amon/tas/gr/v20200729/tas_Amon_IPSL-CM5A2-INCA_historical_r1i1p1f1_gr_185001-201412.nc'

# calculate CDAT spatial average

f = cdms2.open(fn)
tas = f('tas', time=slice(0, 1))
f.close()
tas = tas[0]
tas_cdat_weighted = cdutil.averager(tas, axis='xy', weights='weighted')

# calculate xcdat spatial average
ds = xcdat.open_dataset(fn)
tas_xcdat_weighted = ds.xcdat.spatial_avg().tas.isel(time=0).load().data

# there is a global average difference
print('cdat value', tas_cdat_weighted)
print('xcdat value', tas_xcdat_weighted)
print('difference', tas_xcdat_weighted - tas_cdat_weighted)
```

> cdat value 284.1609407146412                                                                                                                              
> xcdat value 284.1607
> difference -0.0002351482349354228

Check if I get the same thing using `_get_weights` and `_averager`:
```
# I can get the same thing manually getting the weights
# and calling the averager
weights = ds.spatial._get_weights(axis=['lat', 'lon'], lat_bounds=[-90, 90], lon_bounds=[0, 360])
weighted_averager_with__averager = ds.spatial._averager(ds.tas[0], axis=['lat', 'lon'], weights=weights).load().data

print('xcdat _averager call', weighted_averager_with__averager)
print('difference', weighted_averager_with__averager - tas_cdat_weighted)
```

> xcdat _averager call 284.16067729983047
> difference -0.00026341481071767703

Problem remains. I'll try to calculate the value myself using the xcdat generated weighting matrix (which I believe is the same as the CDAT generated weight matrix):

```
# try manual calculation with xcdat-generated weights
weighted_average = (np.sum(ds.tas[0] * weights) / np.sum(weights)).data
print('steve manual calculation', weighted_average)
print('difference', weighted_average - tas_cdat_weighted)
```

> steve manual calculation 284.16095
> difference 8.992390064577194e-06

The answer is different (and the difference is smaller). 

@tomvothecoder - Do you have ideas about what may be going on. It seems like xcdat is slightly different from CDAT and my manual calculation. The data is stored as a float – maybe that is playing a role?

**Comment by durack1** [comment]
> Can anyone see a reason not to use the latitude bounds in the file?

It's always a good idea to have some sanity checks running >=-90.0, <=90.0, >=-180., <=360., as the garbage that I've seen in some of the (particularly early) CMIP data is always astounding - same with obs data too. The double lon values (same lon value to precision, but different values in the matrix) are another CMIP data quirk favourite of mine

**Comment by pochedls** [comment]
As a to do, I should check the time series differences using [numpy.allclose()](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html).

**Comment by pochedls** [comment]
Reporting back on this...I looped over 18585 file/domain combinations. 

* 288 files had a problem (either didn't load or a spatial average wasn't computed for CDAT/xcdat/both). This left us with 18297 files to compare.
* 18243 / 18297 (99.7%) has CDAT/xcdat spatial average time series within tolerance (within ~0.003 for each time step).
* If I dropped the bounds and manually computed the bounds, 18243/18243 (100%) comparisons were within tolerance. 
* xcdat was faster 9684 times (53%) and CDAT was faster 8613 times (47%), but the speed was strongly correlated (r = 0.82)

For the 288 files:
* The following directories did not load with `xcdat.open_mfdataset()`
   * /p/css03/esgf_publish/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r13i1p1/v20131231/tas/
   * /p/css03/esgf_publish/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r14i1p1/v20130315/tas/
   * /p/css03/cmip5_css01/data/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r7i1p1/v20120502/tas/
   * /p/css03/esgf_publish/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r3i1p1f1/Amon/tas/gr/v20200730/
   * /p/css03/scratch/cmip6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Amon/tas/gn/v20190914/

* xcdat failed to produce spatial averages for the following (all 21 domains):
    * /p/css03/cmip5_css02/data/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r1i1p1/tas/1/
    * /p/css03/esgf_publish/CMIP6/CMIP/UA/MCM-UA-1-0/historical/r1i1p1f1/Amon/tas/gn/v20190731/
    * /p/css03/esgf_publish/CMIP6/CMIP/UA/MCM-UA-1-0/historical/r1i1p1f2/Amon/tas/gn/v20190731/

* Both CDAT and xcdat failed to average the following (all 21 domains):
    * /p/css03/esgf_publish/CMIP6/CMIP/MPI-M/ICON-ESM-LR/historical/r1i1p1f1/Amon/tas/gn/v20210215/
    * /p/css03/esgf_publish/CMIP6/CMIP/MPI-M/ICON-ESM-LR/historical/r2i1p1f1/Amon/tas/gn/v20210215/
    * /p/css03/esgf_publish/CMIP6/CMIP/MPI-M/ICON-ESM-LR/historical/r3i1p1f1/Amon/tas/gn/v20210215/
    * /p/css03/esgf_publish/CMIP6/CMIP/MPI-M/ICON-ESM-LR/historical/r4i1p1f1/Amon/tas/gn/v20210215/
    * /p/css03/esgf_publish/CMIP6/CMIP/MPI-M/ICON-ESM-LR/historical/r5i1p1f1/Amon/tas/gn/v20210215/

* The following failed for both CDAT and xcdat for a subset of domains (Sahel, GoG, SAmo):
    * /p/css03/esgf_publish/CMIP6/CMIP/NUIST/NESM3/historical/r1i1p1f1/Amon/tas/gn/v20190630/
    * /p/css03/esgf_publish/CMIP6/CMIP/NUIST/NESM3/historical/r2i1p1f1/Amon/tas/gn/v20190628/
    * /p/css03/esgf_publish/CMIP6/CMIP/NUIST/NESM3/historical/r3i1p1f1/Amon/tas/gn/v20190630/
    * /p/css03/esgf_publish/CMIP6/CMIP/NUIST/NESM3/historical/r4i1p1f1/Amon/tas/gn/v20190629/
    * /p/css03/esgf_publish/CMIP6/CMIP/NUIST/NESM3/historical/r5i1p1f1/Amon/tas/gn/v20190628/

Overall, I don't think there are issues with xcdat's spatial averaging functionality. @tomvothecoder - should I break some of this into separate issues or just keep updating this thread until I understand each problem?

**Comment by durack1** [comment]
Nice @pochedls!

It might be useful to add non-atmospheric grids as your problem counts will jump markedly

**Comment by chengzhuzhang** [comment]
@pochedls nice work! I'm recently looping over models with E3SM Diags, and found that ICON-ESM-LR somehow submitted unstructured grids, so it is expected that either xarray nor cdms2 could open its five ensembles.

**Comment by pochedls** [comment]
> Nice @pochedls!
> 
> It might be useful to add non-atmospheric grids as your problem counts will jump markedly

The spatial averaging functionality was designed to work with rectilinear grids.

> @pochedls nice work! I'm recently looping over models with E3SM Diags, and found that ICON-ESM-LR somehow submitted data on unstructured grids, so it is expected that either xarray nor cdms2 could open its five ensembles.

Thanks @chengzhuzhang - yeah - I think most of the problems I list above are due to specific model problems.

**Comment by tomvothecoder** [comment]
> Overall, I don't think there are issues with xcdat's spatial averaging functionality. @tomvothecoder - should I break some of this into separate issues or just keep updating this thread until I understand each problem?

Great work @pochedls! I think we can continue updating this thread until we have enough information to warrant new GH issues.

**Comment by pochedls** [comment]
@tomvothecoder - I'm slowly whittling down this list. I wanted to see if you could look at one of these to see if it is a simple problem or warrants a ticket. When I call `spatial_avg` on the following file, I get: 

> KeyError: "The data variable 'tas' is missing the '['lat', 'lon']' dimension, which is required for spatial averaging."

For some reason, cf_xarray isn't generating an axes list. This seems to be a one-off problem with this file, though it isn't immediately obvious why (I don't see a problem with the metadata). 


```
ds = xcdat.open_mfdataset('/p/css03/cmip5_css02/data/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r1i1p1/tas/1/*.nc')
ds.tas.cf.axes
```

> {}

**Comment by tomvothecoder** [comment]
>     KeyError: "The data variable 'tas' is missing the '['lat', 'lon']' dimension, which is required for spatial averaging."

> For some reason, cf_xarray isn't generating an axes list. This seems to be a one-off problem with this file, though it isn't immediately obvious why (I don't see a problem with the metadata).

In that dataset, the `axis` attribute might not be set for those dimensions so `cf_xarray` isn't listing them under `ds.tas.cf.axes`. I'll take a look and let you know if this is true.

**Comment by tomvothecoder** [comment]
```
ds = xcdat.open_mfdataset('/p/css03/cmip5_css02/data/cmip5/output1/ICHEC/EC-EARTH/historical/mon/atmos/Amon/r1i1p1/tas/1/*.nc')

# Check the dataset's CF metadata with cf_xarray -- CF Axes is n/a
# -----------------------------------------------------------------
Coordinates:
- CF Axes:   X, Y, Z, T: n/a

- CF Coordinates: * longitude: ['lon']
                  * latitude: ['lat']
                    vertical, time: n/a

- Cell Measures:   area, volume: n/a

- Standard Names: * latitude: ['lat']
                  * longitude: ['lon']

- Bounds:   n/a

Data Variables:
- Cell Measures:   area, volume: n/a

- Standard Names:   air_temperature: ['tas']

- Bounds:   lat: ['lat_bnds']
            latitude: ['lat_bnds']
            lon: ['lon_bnds']
            longitude: ['lon_bnds']
            time: ['time_bnds']

# Check the attributes for "lat" and "lon" -- confirmed no "axis" attr set
# -----------------------------------------------------------------
ds.lat.attrs

{'long_name': 'latitude',
 'units': 'degrees_north',
 'standard_name': 'latitude',
 'bounds': 'lat_bnds'}

ds.lon.attrs

{'long_name': 'longitude',
 'units': 'degrees_east',
 'standard_name': 'longitude',
 'bounds': 'lon_bnds'}

# Set "lat" "axis" attribute
# -----------------------------------------------------------------
ds.lat.attrs["axis"] = "Y"
ds.lon.attrs["axis"] = "X"

# Check the dataset with cf_xarray again -- the axes is now found
# -----------------------------------------------------------------
ds.lat.cf

Coordinates:
- CF Axes: * X: ['lon']
           * Y: ['lat']
             Z, T: n/a

- CF Coordinates: * longitude: ['lon']
                  * latitude: ['lat']
                    vertical, time: n/a

- Cell Measures:   area, volume: n/a

- Standard Names: * latitude: ['lat']
                  * longitude: ['lon']

- Bounds:   n/a

Data Variables:
- Cell Measures:   area, volume: n/a

- Standard Names:   air_temperature: ['tas']

- Bounds:   X: ['lon_bnds']
            Y: ['lat_bnds']
            lat: ['lat_bnds']
            latitude: ['lat_bnds']
            lon: ['lon_bnds']
            longitude: ['lon_bnds']
            time: ['time_bnds']
```

We can probably improve the `KeyError` so that it says something like:
`KeyError: "cf_xarray could not find an X and/or Y axis. Make sure the data variable 'tas' has X and Y axis coordinates and the 'axis' attribute is set for both."`

**Comment by durack1** [comment]
You also have a `T` coord, so in addition to the `KeyError: "Could not find an X and/or Y axis for spatial averaging` might want to add `T`(and `Z`).

Thinking about this a little, it is basically what I had in mind with #200, so more than happy to engage in the case that rather than just solving this spatial averaging issue, it's done in a more complete (all coords) way. As an FYI, I have been polling out full CMIP6 archive, and have been collecting a bunch of weird edge cases that have barfed with `xcdat/xr` reads, after which I default to `cdms2` before skipping if that fails. In many instances when `xr` has failed, `cdms2` works

**Comment by tomvothecoder** [comment]
> You also have a T coord, so in addition to the KeyError: "Could not find an X and/or Y axis for spatial averaging might want to add T(and Z).

Thanks @durack1. Currently, XCDAT's spatial averaging only operates on rectilinear grids. If we extend spatial averaging to support other axes/dimensions, we will make sure to update the `KeyError`.

Notes in the `_get_weights()` method:
https://github.com/XCDAT/xcdat/blob/c01b7d298a181e4385ec3aba3d265007a172cafe/xcdat/spatial.py#L317-L322

> Thinking about this a little, it is basically what I had in mind with https://github.com/XCDAT/xcdat/issues/200, so more than happy to engage in the case that rather than just solving this spatial averaging issue, it's done in a more complete (all coords) way

You also mentioned #200 being related to #183. If it makes sense, we'll need to figure out a way to handle the different axes that might share the same attributes (e.g., `zlon` and `lon`). I plan on looking into these issues soon.

> As an FYI, I have been polling out full CMIP6 archive, and have been collecting a bunch of weird edge cases that have barfed with xcdat/xr reads, after which I default to cdms2 before skipping if that fails. In many instances when xr has failed, cdms2 works

It might be a good idea to open up a separate issue and list the errors thrown by `xcdat/xr`. For example, at the moment, `xcdat.open_dataset()/open_mfdataset()` automatically attempts to generate bounds for lat/lon/time for the Dataset. Maybe in some cases, `cf_xarray` isn't finding these axes because their attributes aren't CF compliant or they conflict?

Also, I plan on making bounds generation optional in #220.

**Comment by durack1** [comment]
> I plan on looking into these issues soon.

No problem, when you get to this, happy to engage. Currently, I have 27 edge cases to follow up on, and I am yet to ascertain whether this is related to `xcdat` (ala #215) or an underlying `xr.*open*` issue. My process should be complete in a ~week, so can coalesce that information when required

**Comment by pochedls** [comment]
@tomvothecoder: [This comment](https://github.com/XCDAT/xcdat/issues/166#issuecomment-1082507179) is updated with an explanation for each difference. Based on today's conversation, I don't think this small subset of issues can generically be addressed in xcdat. I'm closing this issue.
