### ISSUE TITLE
Update CDAT repo with deprecation warning and link to XCDAT

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#175]
### Describe your documentation update

https://github.com/CDAT/cdat

**Comment by durack1** [comment]
@tomvothecoder it may be prudent to do this across all the CDAT submodules as well:
https://github.com/CDAT/cdms
https://github.com/CDAT/cdtime
https://github.com/CDAT/cdutil
https://github.com/CDAT/genutil
https://github.com/CDAT/cdat_info
https://github.com/CDAT/vcs
https://github.com/CDAT/vcsaddons
https://github.com/CDAT/cdms_manual
https://github.com/CDAT/vcdat

https://github.com/CDAT/cd77
https://github.com/CDAT/cdp
https://github.com/CDAT/EzGet
https://github.com/CDAT/lats
https://github.com/CDAT/libcf
https://github.com/CDAT/thermo

**Comment by tomvothecoder** [comment]
Thanks @durack1, will make sure to update the READMEs in those repos as well.

**Comment by durack1** [comment]
@tomvothecoder perfect, thanks for doing this!
