### ISSUE TITLE
add osx-arm64 conda build

### ISSUE THREAD

**Issue by durack1** [xCDAT/xcdat#180]
It seems that [the current 0.1.0 release is a noarch](https://anaconda.org/conda-forge/xcdat/files), so should work across all platforms.

If platform builds will be generated, It'd be great if `osx-arm64` conda builds could be added, see https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

**Comment by tomvothecoder** [comment]
This should be handled by the latest release #321.
