### ISSUE TITLE
[Bug]: AttributeError: ...multiple values for 'longitude'

### ISSUE THREAD

**Issue by pochedls** [xCDAT/xcdat#183]
Not really a bug necessarily, but a behavior we should think about...

### What versions of software are you using?

-   Package Version: I'm on PR #107, but this likely affect main. 

### What are the steps to reproduce this issue?

```
fn = '/p/user_pub/climate_work/pochedley1/cesm2le/TS/b.e21.BSSP370smbb.f09_g17.LE2-1301.020.cam.h0.TS.209501-210012.nc'
ds = xcdat.open_dataset(fn)
```

> AttributeError: cf_xarray can't wrap attribute 'dims' because there are multiple values for 'longitude'. There is no unique mapping from 'longitude' to a value in 'dims'.

`ncdump -h /p/user_pub/climate_work/pochedley1/cesm2le/TS/b.e21.BSSP370smbb.f09_g17.LE2-1301.020.cam.h0.TS.209501-210012.nc`

> 	double zlon(zlon) ;
> 		zlon:_FillValue = -900. ;
> 		zlon:long_name = "longitude" ;
> 		zlon:units = "degrees_east" ;
> 		zlon:bounds = "zlon_bnds" ;

### What happens? Any logs, error output, etc?

It seems that since both `lon` and `zlon` have `long_name = "longitude"` they conflict. `zlon` is used to [denote zonal averaging](https://www.cesm.ucar.edu/CESM2-LENS2/).

### What were you expecting to happen?

Maybe annoying side effects, but I want it to at least open the dataset. 

### Any other comments?

The ideas that come to mind: 
* Maybe this could simply be opened with xarray - I think subsequent xcdat functionality would work - right?
* Try to detect this situation and deal with it. I think there is a good argument for not doing this (this is a pretty specific issue). I'd be curious if E3SM has this issue for some output. 
* We could choose the coordinates to handle if `data_var` is populated (then we would know to use `lon` instead of `zlon`).

**Comment by tomvothecoder** [comment]
Related to #285

**Comment by pochedls** [comment]
I just wanted to note that I hit this error message when using the regridder (use the code in https://github.com/xCDAT/xcdat/issues/356 with the dataset below).

> AttributeError: cf_xarray can't wrap attribute 'dims' because there are multiple values for 'X'. There is no unique mapping from 'X' to a value in 'dims'.

* /p/css03/esgf_publish/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/historical/r1i1p1f1/SImon/siconc/gn/v20180701/

It's possible that efforts to address this issue (e.g., https://github.com/xCDAT/xcdat/pull/343) will fix the regridding issue.
