### ISSUE TITLE
[FEATURE]: Add `matplotlib` to conda dev env

### ISSUE THREAD

**Issue by tomvothecoder** [XCDAT/xcdat#195]
### Is your feature request related to a problem?

`matplotlib` is required as a dependency for the xarray `.plot()` method to work. We should add it to the conda dev env (`dev.yml`) so that developers can perform QA with `matplotlib` if needed.

**Comment by pochedls** [comment]
@tomvothecoder - I didn't comment on this in the meeting. Do we actually depend on matplotlib anywhere in xcdat? I know it would be convenient for people to not have to add it (e.g., conda install matplotlib), but I also don't think this is technically a dependency. I guess one justification could be that we always want xcdat to work with matplotlib (and whatever added dependencies result)?

**Comment by tomvothecoder** [comment]
@pochedls We actually don't have any `matplotlib` dependencies in `xcdat`, so we shouldn't include it the package's dependencies. It would still be useful in the Conda dev env (`dev.yml`) so we can do some QA using the `matplotlib` if needed.

Thanks for raising these points, I'll drop `matplotlib`.

> I guess one justification could be that we always want xcdat to work with matplotlib (and whatever added dependencies result)?

This is one justification for including `matplotlib`, but if `xarray` doesn't already include it, then `xcdat` shouldn't either (unless we have plotting APIs that depend on it, which I don't think we ever will).
