### ISSUE TITLE
[FEATURE]:  Add averages with time dimension removed

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#201]
### Is your feature request related to a problem?
- It would be really handy, if this feature can include the capability to calculate weighted temporal average. Right now in `xarray`, one still has to generates the `weights` and then do something like `(d * weights).groupby("time.month").sum(dim="time")` I think `temporal_average` can cover this case straightforwardly? perhaps we can add a `mean` mode in addition or enable this if neither "climatology" nor "timeseries" is supplied?

_Originally posted by @chengzhuzhang in https://github.com/XCDAT/xcdat/issues/107#issuecomment-1069621197_

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by tomvothecoder** [comment]
Hi @chengzhuzhang, you mentioned "It would be really handy, include the capability to calculate weighted temporal average". 

From my understanding, this should be satisfied with the current implementation of `_temporal_avg()` using `weighted=True`.
https://github.com/XCDAT/xcdat/blob/17c7d97e41cf5fcc1cb851bf4f03f439391924f0/xcdat/temporal.py#L637-L649

> Right now in xarray, one still has to generates the weights and then do something like (d * weights).groupby("time.month").sum(dim="time")

Weights are generated and applied to the data variable in the `_averager()` method before grouping:
https://github.com/XCDAT/xcdat/blob/17c7d97e41cf5fcc1cb851bf4f03f439391924f0/xcdat/temporal.py#L868-L875

Weights are generated using `_get_weights()`:
https://github.com/XCDAT/xcdat/blob/17c7d97e41cf5fcc1cb851bf4f03f439391924f0/xcdat/temporal.py#L1216-L1265

Let me know if I'm missing something here.

**Comment by chengzhuzhang** [comment]
Hey Tom, I should have clarified. The simple application is just to generate one time-averaged snapshot (with time coordinate collapsed) for time-series input.

**Comment by chengzhuzhang** [comment]
Hey Tom, I think it should do. Applying weights is only needed for monthly and yearly time-series (if the length of the months is uneven and weighted != False)

**Comment by tomvothecoder** [comment]
After giving this some thought, I think a more lightweight solution is expose an API for users to get temporal weights so that we don't have to write an API for simple weighted means (which will probably end up involving more logic than the example below).

Example:
```
ds = xcdat.open_dataset("path_to_dataset")

dv = ds.ts

# This can be a property like "weights" or a method like "get_weights()"
weights = ds.temporal.weights

dv_wt_avg = (dv * weights).groupby("time.month").sum(dim="time") 
```

I prefer this solution because users will leverage native xarray APIs for simpler operations, which in turn helps them familiarize themselves with the capabilities and syntax of xarray. 
Also, the lines of code is fairly minimal in this case.

**Comment by chengzhuzhang** [comment]
Thank you for your input.  I was thinking about a similar utility as the cdutil.averager() function. for a simple time averaging case, the axis='t', either with generated weights, equal weights or a user supplied weights. It would be the best if we can naturally fit this in current implementation without further investing a separate routine. I guess i will think more, and we can discuss in the next xcdat meeting.

**Comment by tomvothecoder** [comment]
Thanks @chengzhuzhang. I should've clarified what it means to "collapse" the time coordinates, but it all makes sense to me now!

What you're suggesting for simple time averaging is similar to the current xcdat spatial averaging implementation. For spatial averaging, weights can be generated or user-supplied (we decided to remove equal weighting), and the lat and/or lon axis is collapsed. This behavior is similar to `cdutil.averager()`.

For simple time averaging, we do the same thing but with the time coords collapsed instead. To achieve this, we use xarray's [`.weighted()` ](https://xarray.pydata.org/en/stable/generated/xarray.DataArray.weighted.html#) method with the chained aggregation method `.mean()`.

For example, instead of doing this (which doesn't collapse the time coordinates):
```
weights = ds.temporal.weights
dv_wt_avg = (dv * weights).groupby("time.month").sum(dim="time") 
```

we would do this
```
# xcdat generated weights, but they can also be user supplied
weights = ds.temporal.weights
dv_weighted = dv.weighted(weights).mean("time")

# If we want unweighted means, simply don't use `.weighted()`
dv_unweighted = dv.mean("time")
```

---
This is how it is done in spatial averaging:
https://github.com/XCDAT/xcdat/blob/79c488ea890febc422fe2e38b85c4e9dc7c72565/xcdat/spatial.py#L712-L717

I'll spend think about if it makes sense to wrap this in xCDAT (e.g., do we need to cover edge cases like spatial averaging? can the user achieve this with minimal effort in xarray?), and what the implementation might look like if it does.
