### ISSUE TITLE
[FEATURE]: Rename `spatial_avg.py` to `spatial.py`

### ISSUE THREAD

**Issue by tomvothecoder** [XCDAT/xcdat#206]
### Is your feature request related to a problem?

While working on #107, I noticed that I was adding temporal functions/methods to `temporal_avg.py` that weren't directly related to the `TemporalAverageAccessor` class. For example, the `TemporalAverageAccessor.center_times()` should actually just be a standalone function that lives in the `.py` module. 

I ended up renaming the file from `temporal_avg.py` to `temporal.py` to store all temporal related functions and classes.

If we want to group functionality based on axes/dimensions, we should also rename `spatial_avg.py` to `spatial.py`.

**Comment by tomvothecoder** [comment]
Hey @pochedls, let me know what you think about this.

**Comment by pochedls** [comment]
> Hey @pochedls, let me know what you think about this.

I like this a lot.

**Comment by tomvothecoder** [comment]
In addition to renaming the files, we can also rename the accessor classes so that we can keep methods like `center_times()` inside the classes, instead of separating them out as standalone functions.

For example, we can rename `TemporalAverageAccessor` to `TemporalAccessor` and `SpatialAverageAccessor` to `SpatailAccessor`.

I am leaning towards this route too.

**Comment by durack1** [comment]
@tomvothecoder I think this is ideal, you may want median, min, max, ..., operations in addition to average so more general axes/spatial and time coordinate/temporal is a smart more general move. Just thinking aloud, I wonder if vertical would be folded into axes, or would be its own class?

@pochedls has the arbitrary index discussion come up anywhere, so what I mean is captured in https://github.com/CDAT/cdat/issues/1288
