### ISSUE TITLE
[FEATURE]: Add `average()`, `climatology()`, and `departures()` to temporal accessor

### ISSUE THREAD

**Issue by tomvothecoder** [XCDAT/xcdat#219]
### Is your feature request related to a problem?

Currently, calling temporal averaging requires using `.temporal.temporal_avg()` The user has to pass a `mode` arg with a value of either `"time_series"` for time series averaging, or `"climatology"` for calculating climatology. 

Both operations were encapsulated under `temporal_avg()` because they share the same logic. However, the temporal averaging API could be cleaner if we separate each of these operations into separate methods, both of which call `temporal_avg()` with the `mode` arg already specified under the hood.

### Describe the solution you'd like

1. Make `temporal_avg()` a private API (`_temporal_avg()`).
2. Add a method for `climatology()` which calls `_temporal_avg()` with `mode="climatology"`
   - Example: `ds.temporal.climatology("some_var")`
3. Add a method for `average()` which calls `_temporal_avg()` with `mode="time_series"`
   - Example: `ds.temporal.average("some_var")`

### Additional context

Related issue #218

**Comment by lee1043** [comment]
@tomvothecoder excellent, thank you for keeping me in the loop!
