### ISSUE TITLE
[FEATURE]: Update supported spatial `axis` arg keys  generic format

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#225]
### Is your feature request related to a problem?

The valid `axis` arg values of `"lat"` and `"lon"` do not follow the axis naming convention that we adopted with our APIs.

https://github.com/XCDAT/xcdat/blob/79c488ea890febc422fe2e38b85c4e9dc7c72565/xcdat/spatial.py#L47

We implemented a mapping system for axis and coordinates names to their generic axis name.
https://github.com/XCDAT/xcdat/blob/79c488ea890febc422fe2e38b85c4e9dc7c72565/xcdat/axis.py#L14-L25

### Describe the solution you'd like

1. Update valid `axis` arg values from `"lat"` and `"lon"` to `"Y"`/`"y"` and `"X"`/`"x"` 
3. Convert the `axis` arg value to `.upper()` 
4. Map the `axis` arg to the dimension/coordinates in the `xr.Dataset`
5. Update `KeyError` if the CF `axis` attribute is not set for the X and Y axis coordinates
  * Related to https://github.com/XCDAT/xcdat/issues/166#issuecomment-1099382979
    >     We can probably improve the KeyError so that it says something like:
    >     KeyError: "Could not find an X and/or Y axis for spatial averaging. Make sure the data variable 'tas' has X and Y axis  coordinates and the 'axis' attribute is set for both."
  * A reusable convenience function/method might be useful for checking if the `axis` attribute is set for the desired axis in the Dataset. If it isn't, then raise a `KeyError`. `cf_xarray` already throws an error if we try something like `ds.cf["X"]` when the `"X"` axis attr is not set, but the error is ambiguous.

### Additional context

* `cdutil.averager()`'s `axis` arg accepts lowercase generic axis names (`"x"`, `"y"`, `"t"`, etc.)

**Comment by tomvothecoder** [comment]
Hi @pochedls, this was something that cropped up as I was working on the API examples for the upcoming xCDAT presentation.

I recall we initially considered using the generic axis names and we probably should have, but that is in hindsight.

**Comment by pochedls** [comment]
Hi @tomvothecoder - thanks for spotting this. I think I lost track of this feature (I believe you're right that we thought we'd include support for "x"/"y"). Do you want me to try to address this ticket or have you already started?

**Comment by tomvothecoder** [comment]
Hi @pochedls, I started a PR and tagged you for review (PR #226).
