### ISSUE TITLE
[Doc]: Update full name to "Xarray Climate Data Analysis Tools"

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#255]
### Describe your documentation update

We decided to change the full name from "Xarray Extended with Climate Data Analysis Tools" to "Xarray Climate Data Analysis Tools" to reduce the verbosity and make it one-to-one with acronym "xCDAT".

**Comment by lee1043** [comment]
@tomvothecoder sounds great, thank you for the discussion.
