### ISSUE TITLE
[Feature]: Improve error messages when attempting retrieve coords/coord bounds for an axis

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#260]
### Is your feature request related to a problem?

In PR #246, a new method called `_get_coord_var()` was added, which checks if the supplied axis key can be interpreted using the `axis` attribute:
https://github.com/xCDAT/xcdat/blob/350ac8b36c8f2e89c63a70b53626cae43cf6b88e/xcdat/axis.py#L327-L355

However, when attempting to retrieve coord bounds, we raise an ambiguous error message if they aren't found:
https://github.com/xCDAT/xcdat/blob/350ac8b36c8f2e89c63a70b53626cae43cf6b88e/xcdat/bounds.py#L179-L183

### Describe the solution you'd like

There are several reasons for why coord bounds can't be retrieved (https://github.com/xCDAT/xcdat/pull/164#issuecomment-1150152473):

> I plan on opening a separate PR to improve error messages when attempting to fetch coordinate variables or bounds data variables using `cf_xarray` and CF-compliant  "axis" and/or "standard_name" attributes.
>
> This KeyError is possibly being raised because:
> 1. There is no Z coordinate variable
> 2. There is a Z coordinate variable, but the `"axis"` attribute is not set to "Z"
> 3. There is a Z coordinate variable and the `"axis"` attribute is set to "Z", but the `"bounds"` attribute is not set to the name of the bounds data variable 
> 4. The bounds data var doesn't exist and need to be added.

We need a clearer error message based on which case is true.

**Comment by durack1** [comment]
@tomvothecoder FYI, the upcoming Python 3.11 release (October 2022) plans to include "Fine-Grained Error Locations in Tracebacks" which looks like a great improvement over 3.10 and earlier. The `Exception Groups` also looks like a great optimization.

Might be useful to ponder as you're working on this feature

See https://www.python.org/downloads/release/python-3110b3/
