### ISSUE TITLE
[Bug]: “ImportError: Numba needs NumPy 1.21 or less”

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#279]
### What happened?

Related to https://github.com/xCDAT/xcdat/issues/272

The root of this issue is numba’s conda recipe not properly constraining the compatible numpy version based on the numba version.

As a result, conda/mamba sometimes successfully builds the xcdat package with incompatible versions of numba and numpy. We only find out these two packages are incompatible when we `import xcdat`  and get “ImportError: Numba needs NumPy 1.21 or less”.

Related open issues:
- [Need meta-data patches for Numba/NumPy version compatibility? #90](https:/github.com/conda-forge/numba-feedstock/issues/90)
- [numba 0.55.0 on defaults doesn't constrain numpy as expected #7794](https://github.com/numba/numba/issues/7794)
 
Solution: 
- [ ] Constrain `numba>=0.55.2` in the `xcdat` conda-env yml files

Future todo:
- [ ] Remove `numba` once it is properly constrained with numpy

> In addition to that, if there are conda-forge packages that do not have numpy constrained properly for older versions of numba, there is a process for patching the package metadata to fix the issue.  If you can point out which numba packages are installing but then reporting incompatibility, I can make a PR to conda-forge's repodata patch repository to fix them.

[https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pulls](https://urldefense.us/v3/__https:/github.com/conda-forge/conda-forge-repodata-patches-feedstock/pulls__;!!G2kpM7uM-TzIFchu!mmzaZi7VKdvlc_MzfHQqJR6jvPkBVFNykO1zEA7uB-efEsvornkObo4jJa33bWs$)

### Anything else we need to know?

Related to:
https://github.com/conda-forge/xcdat-feedstock/issues/5

### Environment

xcdat = 0.3.0

**Comment by pochedls** [comment]
Thanks Tom – I did hit this issue again with a pretty plain environment `conda create -n xcdat -c conda-forge xcdat ipython matplotlib sklearn` – so I think it will be a benefit to handle this for now.
