### ISSUE TITLE
[Doc]: The documentation should mention the "CF convention" more clearly

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#292]
### Describe your documentation update

I'm expecting xCDAT to help us work with data files following the CF convention, and also give us workaround to still access data files that have problems with the convention

Searching for `CF`, `convention`, `CF convention`, or `cfconvention` in the [documentation](https://xcdat.readthedocs.io/) gave me a few hits (e.g [xcdat.temporal.TemporalAccessor](https://xcdat.readthedocs.io/en/latest/generated/xcdat.temporal.TemporalAccessor.html) or [xcdat.decode_non_cf_time](https://xcdat.readthedocs.io/en/latest/generated/xcdat.decode_non_cf_time.html)) but this is not enough

Handling the **CF convention will be an asset of xcdat and should appear early on and more clearly in the documentation**! 

This may be too old for some people working on xCDAT, but we should remember that before being called the _CF convention_, it was the _GDT convention_, **GDT** being the initials of [Gregory, Drach and Taylor](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_about_the_authors), and Bob Drach was the creator of cdms!

I expect some parts of the documentation will have to mention how (much) they (can) follow CF

**Comment by tomvothecoder** [comment]
Closed by #362 

https://xcdat.readthedocs.io/en/latest/index.html#things-we-are-striving-for
https://xcdat.readthedocs.io/en/latest/faqs.html#what-types-of-datasets-does-xcdat-primarily-focus-on
