### ISSUE TITLE
[Feature]: add matplotlib to standard dependencies

### ISSUE THREAD

**Issue by durack1** [xCDAT/xcdat#305]
### Is your feature request related to a problem?

I am constantly recreating environments, or installing `matplotlib` as an additional library. I am guessing this is likely the same for most `xcdat` users, so why not add this as a dependency?

### Describe the solution you'd like

Add matplotlib to the standard build/dependency list

### Describe alternatives you've considered

Continue to add `.. matplotlib` to `conda create` calls

**Comment by pochedls** [comment]
`xcdat` doesn't depend on matplotlib. It may be convenient for some users, but could also create conflicts for other users.

**Comment by durack1** [comment]
@pochedls exactly, `xcdat` doesn't DEPEND on `matplotlib`, but I do (depend on `matplotlib`) and my guess is that 90+% of users are the same. If it's a standard env, then may as well roll it in, as that way any conflicts will be picked up in the CI testing before a release

**Comment by chengzhuzhang** [comment]
we perhaps can follow what xarray is doing for handling required and recommended/optional dependencies? https://docs.xarray.dev/en/stable/getting-started-guide/installing.html

**Comment by durack1** [comment]
@chengzhuzhang that is a useful page/guidance, lots of stuff I wasn't aware of.

I do wonder whether *most* users use `matplotlib` and if so, then simplify the experience for new users, particularly if many of the jupyter notebook demos are using `matplotlib` in their examples.

Happy to defer to the consensus view here

**Comment by tomvothecoder** [comment]
Closing based on above comment.
