### ISSUE TITLE
[Bug]: Replace static references to "time" for the time dimension name with `self._dim` in TemporalAccessor

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#311]
### What happened?

The `TemporalAccessor` class has static references to "time" as the name of the time dimension. However, datasets can use different names for a time dimension, such as "time_centered", "T", "time_counter", 

Original source:
----
In looking at Test 3, I see another issue here. The time axis needed for temporal operations is not actually assigned as a dimension. I thought this could be fixed by dropping `time_counter` and just using `time_centered`: this would get rid of the multiple time axes which is the issue for Test 1 and 2 and would also be the appropriate coordinate for temporal operations: 

```
import numpy as np, xarray as xr, xcdat as xc
TS_File ='https://thredds-su.ipsl.fr/thredds/dodsC/ipsl_thredds/omamce/TestCases/XCDAT/thetao_CF_1.nc'
ds = xr.open_dataset(TS_File, decode_times=False)
ds['time_counter'] = ds['time_centered']
ds = ds.drop_vars('time_centered')
ds = ds.rename({'time_counter': 'time_centered'})
ds.to_netcdf('test.nc', 'w', 'NETCDF3_CLASSIC')

ds = xc.open_dataset('test.nc')
ds.temporal.group_average('thetao', freq='year', weighted=True)
```

But this yields a different error: 

> AttributeError: 'DataArray' object has no attribute 'time'

@tomvothecoder - do you think this is a separate issue in the temporal averaging logic?

_Originally posted by @pochedls in https://github.com/xCDAT/xcdat/issues/285#issuecomment-1209799854_

### What did you expect to happen?

Temporal averaging should work regardless of the name of the time dimension.

### Minimal Complete Verifiable Example

```python
import numpy as np, xarray as xr, xcdat as xc
TS_File ='https://thredds-su.ipsl.fr/thredds/dodsC/ipsl_thredds/omamce/TestCases/XCDAT/thetao_CF_1.nc'
ds = xr.open_dataset(TS_File, decode_times=False)
ds['time_counter'] = ds['time_centered']
ds = ds.drop_vars('time_centered')
ds = ds.rename({'time_counter': 'time_centered'})
ds.to_netcdf('test.nc', 'w', 'NETCDF3_CLASSIC')

ds = xc.open_dataset('test.nc')
ds.temporal.group_average('thetao', freq='year', weighted=True)
```

### Anything else we need to know?

This is a simple fix that involves updating "time" references to `self._dim`.

https://github.com/xCDAT/xcdat/blob/4c51879a65992e08b29eabd2d31f7332aca78e61/xcdat/temporal.py#L149

### Environment

xcdat = v0.3.0

**Comment by jypeter** [comment]
@tomvothecoder are you detailing somewhere (maybe some place easy to find in the documentation) what will be recognized as a time axis (you mention abov **such as "time_centered", "T", "time_counter"**)?

I'm assuming you **don't make a difference between upper and lowercase**, but maybe you can **have a look at what cdms2 considered a time axis**. There is an isTime() Axis method on page 48 of cdms5.pdf (on of the documents I provided in https://github.com/xCDAT/xcdat/discussions/170) that says:
```
isTime()
Returns true iff the axis is a time axis. ax is a longitude axis if:
• ax.axis==’T’, or
• ax.id[0:4]==’time’, or
• ax.id is in cdms2.axis.time_aliases
```

Note that page 47 also describes `isLevel()`, `isLatitude()` and `isLongitude()`

**Comment by jypeter** [comment]
Note: see example usage of `isTime()` in https://github.com/xCDAT/xcdat/issues/310#issuecomment-1212866276

**Comment by tomvothecoder** [comment]
> @tomvothecoder are you detailing somewhere (maybe some place easy to find in the documentation) what will be recognized as a time axis (you mention above such as "time_centered", "T", "time_counter")?

We mention how we map to coordinates in the Planned Features section, under "Things we are striving for".
- https://xcdat.readthedocs.io/en/latest/index.html#planned-features

> * Robust handling of coordinates and its associated bounds
> 
>   * Coordinate variables are retrieved with ``cf_xarray`` using either the ``"axis"``, ``"standard_name"``, or dimension name attribute
>   * Bounds are retrieved with ``cf_xarray`` using the ``"bounds"`` attr
>   * Ability to operate on both longitudinal axis orientations, [0, 360) and [-180, 180)

The related function is called `.get_axis_coord()` that is used internally and also available as a public function. 
Here is the function (with the docstring) and the related API documentation.

* API Source Code: https://github.com/xCDAT/xcdat/blob/4c51879a65992e08b29eabd2d31f7332aca78e61/xcdat/axis.py#L28-L87
* API Documentation (using docstring): https://xcdat.readthedocs.io/en/latest/_modules/xcdat/axis.html#get_axis_coord
* Intro to cf_xarray: https://cf-xarray.readthedocs.io/en/latest/howtouse.html
* cf_xarray mapping table for "axis" and "standard_name" attrs: https://cf-xarray.readthedocs.io/en/latest/coord_axes.html
