### ISSUE TITLE
[Feature]: Use dimension coordinates from the input data variable in specific xCDAT APIs

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#314]
### Is your feature request related to a problem?

Related #285 and #312, we might need to update how we get the dimension name for a time axis (`self._dim`) in `TemporalAccessor()`.

Instead of getting the time dimension name from the dataset (which can have multiple time axis):
https://github.com/xCDAT/xcdat/blob/4c51879a65992e08b29eabd2d31f7332aca78e61/xcdat/temporal.py#L149

We can get just the single time axis for the data variable that is being temporally averaged:
`self._dim = get_axis_coord(self._data_var, "T").name`

_Originally posted by @tomvothecoder in https://github.com/xCDAT/xcdat/issues/312#issuecomment-1215430614_

**Comment by pochedls** [comment]
@tomvothecoder - I'm wondering if this could/should be more general to all dimensions (e.g., also `X` or `Y`). This issue can affect other axes (e.g., [here](https://github.com/xCDAT/xcdat/issues/285#issuecomment-1200282940)). I have not seen problems with spatial averaging, but it seems like it could (e.g., [here](https://github.com/xCDAT/xcdat/blob/main/xcdat/spatial.py#L252)). Maybe the `data_var` can be passed into some of these functions (as an optional argument?) and used in `get_bounds`?

**Comment by tomvothecoder** [comment]
Good point @pochedls. Yes, this should be applied to the `SpatialAccessor` and its methods as well.

For accessor classes:
* Store the name of the user specified `data_var` as a class attr so it can be referenced in the class methods (no need to pass around as method args)

For `get_bounds`:
* Update to handle cases where the dataset has multiple axis dimensions
* Add `data_var` string keyword arg to fetch bounds for a specific axis for a data var

**Comment by tomvothecoder** [comment]
The proposed solution in this issue actually won't fix the issue of trying to map the desired axis coord variable for a dim because DataArrays can also have multiple coord vars mapped to a dim like Datasets (Datasets shares coords from its DataArrays).

Example:
```python
import cf_xarray as cf
import xarray as xr
import xcdat as xc

#%%
# Test2 - Remove attributes referring to non-existing bounds
# This file is CF compliant (https://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl)
"""
- https://github.com/xCDAT/xcdat/issues/285#issuecomment-1209768695
"""
filepath2 = "https://thredds-su.ipsl.fr/thredds/dodsC/ipsl_thredds/omamce/TestCases/XCDAT/thetao_CF.nc"

#%%
ds2 = xr.open_dataset(filepath2)

#%%
# 1. Attempt to get "T" axis coordinate variable in the Dataset
ds2.cf["T"]
# KeyError: "Receive multiple variables for key 'T': {'time_centered', 'time_counter'}. Expected only one. Please pass a list ['T'] instead to get all variables matching 'T'."

#%%
# 2. Check the Dataset's cf_xarray mapping 
ds2.cf

"""
Coordinates:
- CF Axes:   T: ['time_centered', 'time_counter']
             X, Y, Z: n/a

- CF Coordinates:   longitude: ['nav_lon']
                    latitude: ['nav_lat']
                  * vertical: ['olevel']
                    time: ['time_centered', 'time_counter']

- Cell Measures:   area, volume: n/a

- Standard Names:   latitude: ['nav_lat']
                    longitude: ['nav_lon']
                    time: ['time_centered', 'time_counter']

- Bounds:   n/a

Data Variables:
- Cell Measures:   area, volume: n/a

- Standard Names:   sea_water_conservative_temperature: ['thetao']

- Bounds:   T: ['time_centered_bounds']
            time: ['time_centered_bounds']
            time_centered: ['time_centered_bounds']

"""

#%%
# 3. Attempt to get "T" axis coordinate variable in the DataArray
ds2.thetao.cf["T"]
# KeyError: "Receive multiple variables for key 'T': {'time_centered', 'time_counter'}. Expected only one. Please pass a list ['T'] instead to get all variables matching 'T'."

#%%
# 4. Check the DataArray's cf_xarray mapping
ds2.thetao.cf
"""
Coordinates:
- CF Axes:   T: ['time_centered', 'time_counter']
             X, Y, Z: n/a

- CF Coordinates:   longitude: ['nav_lon']
                    latitude: ['nav_lat']
                  * vertical: ['olevel']
                    time: ['time_centered', 'time_counter']

- Cell Measures:   area, volume: n/a

- Standard Names:   latitude: ['nav_lat']
                    longitude: ['nav_lon']
                    time: ['time_centered', 'time_counter']

- Bounds:   n/a
"""

```

We need to figure out a sensible way of choosing the correct coord var for a dim in a DataArray for `SpatialAccessor` and `TemporalAccessor`. This might involve using the dimension name as mentioned [here](https://github.com/xCDAT/xcdat/issues/285#issuecomment-1209768695): 

> 
pass in a list, e.g., ds.cf[["T"]] instead of ds.cf["T"]. You could check if one of the time coordinates is a dimension by checking this intersection: list(set(ds.cf[["T"]].coords) & set(ds.cf[["T"]].dims)). If one axis satisfies this criteria, you could then choose this axis (e.g., updating the selection [here](https://github.com/xCDAT/xcdat/blob/main/xcdat/dataset.py?rgh-link-date=2022-08-09T19%3A05%3A18Z#L449)) within _has_cf_compliant_time.

**Comment by pochedls** [comment]
@tomvothecoder  - everything is checking out, but there is one weird behavior that I have not yet figured out (it only seems to affect on dataset so far).

```
import xcdat as xc

dpath = '/p/css03/esgf_publish/CMIP6/CMIP/NASA-GISS/GISS-E3-G/historical/r1i1p1f1/Amon/tas/gr/v20220727/*nc' 
ds = xc.open_mfdataset(dpath)
ds.tas.shape
```
> (180, 180, 288) 

But for xcdat 0.3.3, I get: 

> (1980, 180, 288)

Do you think this is because the time units vary by file (e.g., `days since 1850-01-01` versus `days since 1950-01-01`)?
