### ISSUE TITLE
[Bug]: Error from climatology calculation when getting it multiple times

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#327]
### What happened?

When calculate seasonal mean climate and annual cycle in one script, following annual cycle calculation is reporting error. 

### What did you expect to happen?

I was presuming calculating seasonal mean climate and annual cycle should not influence to each other, as I am outputting them to different variables. 

### Minimal Complete Verifiable Example

```python
import xcdat
infile = "/p/css03/esgf_publish/CMIP6/CMIP/CSIRO-ARCCSS/ACCESS-CM2/historical/r1i1p1f1/Amon/ts/gn/v20191108/ts_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc"
d = xcdat.open_dataset(lf, data_var=var)

d_ac = d.temporal.climatology(var, freq="month", weighted=True)  # okay

d_clim = d.temporal.climatology(var, freq="season", weighted=True, season_config={"dec_mode": "DJF", "drop_incomplete_djf": True},)  # okay

d_ac = d.temporal.climatology(var, freq="month", weighted=True)  # error when repeat after get seasonal climatology
```

### Relevant log output

```python
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
MergeError                                Traceback (most recent call last)
File ~/.conda/envs/pcmdi_metrics_dev_2/lib/python3.9/site-packages/xarray/core/dataarray.py:3554, in DataArray._inplace_binary_op(self, other, f)
   3553 try:
-> 3554     with self.coords._merge_inplace(other_coords):
   3555         f(self.variable, other_variable)

File ~/.conda/envs/pcmdi_metrics_dev_2/lib/python3.9/contextlib.py:119, in _GeneratorContextManager.__enter__(self)
    118 try:
--> 119     return next(self.gen)
    120 except StopIteration:

File ~/.conda/envs/pcmdi_metrics_dev_2/lib/python3.9/site-packages/xarray/core/coordinates.py:190, in Coordinates._merge_inplace(self, other)
    185 prioritized = {
    186     k: (v, None)
    187     for k, v in self.variables.items()
    188     if k not in self.xindexes
    189 }
--> 190 variables, indexes = merge_coordinates_without_align(
    191     [self, other], prioritized
    192 )
    193 yield

File ~/.conda/envs/pcmdi_metrics_dev_2/lib/python3.9/site-packages/xarray/core/merge.py:420, in merge_coordinates_without_align(objects, prioritized, exclude_dims, combine_attrs)
    418 # TODO: indexes should probably be filtered in collected elements
...
   3562 return self

MergeError: Automatic alignment is not supported for in-place operations.
Consider aligning the indices manually or using a not-in-place operation.
See https://github.com/pydata/xarray/issues/3910 for more explanations.
```

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.71.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.8.1

xarray: 2022.6.0
pandas: 1.4.3
numpy: 1.21.3
scipy: 1.9.0
netCDF4: 1.6.0
pydap: None
h5netcdf: None
...
conda: None
pytest: 6.2.5
IPython: 8.4.0
sphinx: None

**Comment by lee1043** [comment]
I am not sure if this bug is related to https://github.com/xCDAT/xcdat/issues/325

**Comment by tomvothecoder** [comment]
Thanks for reporting these bugs Jiwoo.

My initial inclination is that the referenced dataset in the operations is by pointer rather than a deep copy, so subsequent operations affect the original dataset. If this is correct, it should be an easy fix!

I will investigate both soon.

**Comment by gleckler1** [comment]
Excellent.  A follow on to verify will be that the monthly (12) climatology works when selecting a period that is a subset of the full time series.   One of my test was working with the full time series but not when selecting a shorter period.   It does work on seasonal clims.
