### ISSUE TITLE
[Doc]: syntax highlighting in notebooks

### ISSUE THREAD

**Issue by zmoon** [xCDAT/xcdat#360]
### Describe your documentation update

The example notebooks would look a bit nicer in the docs with syntax highlighting. `ipython` needs to be included in the conda env to get highlighting when using nbsphinx. 

https://nbsphinx.readthedocs.io/en/0.8.9/installation.html#Pygments-Lexer-for-Syntax-Highlighting

**Comment by tomvothecoder** [comment]
@zmoon, I'm happy to see you're checking out `xcdat`! Thank you for this suggestion, I'll look into it.

Also let us know if you need anything.
