### ISSUE TITLE
[Bug]: data array variable name for keep_weights differs 

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#377]
### What happened?

![screenshot_xcdat_test](https://user-images.githubusercontent.com/17091564/199346454-549efb70-ccad-46c2-a9cf-59fec1b593a5.png)

Note: dm_x is a dataset 

### What did you expect to happen?

I was expecting regardless of given coordinates, (x, y, t) or (x, y), variable name for spatial weights to be consistent as `lat_lon_wts`. I don't know if this was intended or not. 

### Environment

xcdat v0.3.3

**Comment by pochedls** [comment]
Just noting that this might be related to: https://github.com/xCDAT/xcdat/discussions/296#discussioncomment-4030631

**Comment by tomvothecoder** [comment]
I confirmed this is unrelated to #296, and it affects datasets that have been subsetted.

By subsetting the dataset on the first time step, it turns `time` into a singleton that is "shared" coordinate point for all other coordinates. Notice in the example below, the `longitude` coordinate variable has access to the `time`.

```
ds_sub = ds.isel(time=0)
print(ds_sub.longitude)

<xarray.DataArray 'longitude' (longitude: 360)>
array([-179.5, -178.5, -177.5, ...,  177.5,  178.5,  179.5], dtype=float32)
Coordinates:
    time       object 1870-01-16 11:59:59.505615
  * longitude  (longitude) float32 -179.5 -178.5 -177.5 ... 177.5 178.5 179.5
Attributes:
    units:          degrees_east
    long_name:      Longitude
    standard_name:  longitude
    bounds:         longitude_bnds
```


Here's the related spatial averaging function that combines weights and assigns the name:

https://github.com/xCDAT/xcdat/blob/41bde880ceff6866523515599f9d9cafd89aa772/xcdat/spatial.py#L656-L660

The name of weights is based on the coordinate keys, with `_wts` appended to the end. `time` is incorrectly picked up and appended to the name of the weights (e.g., `lat_lon_time_wts`).

This should be an easy fix.
