### ISSUE TITLE
[Feature]: Allow user selection of reference period in departures

### ISSUE THREAD

**Issue by pochedls** [xCDAT/xcdat#387]
### Is your feature request related to a problem?

The current departures functionality determines the anomalies relative to the average value over the full time series. 

Climate scientists often look at the departures relative to a specific period (rather than the full period). For example, see [IPCC AR6 WG1 Fig. 1.12](https://www.ipcc.ch/report/ar6/wg1/figures/chapter-1/figure-1-12/) which shows the global mean surface temperature departures relative to the average temperature over 1850 – 1900. This shows zero **average** anomaly between 1850 and 1900 and emphasizes the rapid warming that follows. 

We should make it possible for xCDAT users to do this kind of calculation easily. 

### Describe the solution you'd like

xCDAT should allow for flexible selection of the climatological reference period with which to define departures. I think there are several non-mutually exclusive ways to accomplish this:

* Allow the user to provide a a custom climatology when calculating departures, e.g., `ds.temporal.departures(data_var, freq, climatology=ds_climo)`
* Allow the user to specify a climatological base period when calculating departures, e.g., `ds.temporal.departures(data_var, freq, reference_period=("1850-01-01", "1899-12-31"))`
* Or both (possibly by augmenting climatology functionality to accept a `reference_period`, i.e., `ds.temporal.climatology(data_var, freq, reference_period=("1850-01-01", "1899-12-31"))`

### Describe alternatives you've considered

An alternative manual method would entail:

* Subset the dataset of interest to the climatological reference period (`ds_climo = ds.sel("1850-01-01", "1899-12-31")`)
* Take the climatology of this subsetted data (`ds_climo = ds.temporal.group_average(data_var, freq="month")`)
* Somehow subtract this climatology from the original timeseries (not sure how to do this or if this would work): `ds_departure[data_var] = ds[data_var] - ds_climo[data_var]`

### Additional context

- Related discussion: https://github.com/xCDAT/xcdat/discussions/404
- Jiwoo's xarray+xcdat implementation: https://github.com/xCDAT/xcdat_test/blob/main/cookbook/seasonal_departure_from_baseline_clim.ipynb

**Comment by tomvothecoder** [comment]
I'm revisiting this issue today. Thanks again for the detailed description Steve.

It doesn't look that hard to implement (I think).

**Comment by chengzhuzhang** [comment]
Yes, Steve's description is really helpful. I'm wondering if selecting time slice is in general useful for any functions under `temporal` accessor, which might need to be considered in the implementation.

**Comment by lee1043** [comment]
@tomvothecoder Hope this updated [cookbook](https://github.com/xCDAT/xcdat_test/blob/67f2285312a84e0aeab381dbd51955729d925095/cookbook/seasonal_departure_from_baseline_clim.ipynb) to be helpful.

**Comment by tomvothecoder** [comment]
> Yes, Steve's description is really helpful. I'm wondering if selecting time slice is in general useful for any functions under `temporal` accessor, which might worth to be considered in the implementation.

@chengzhuzhang, the public temporal accessor APIs share the same underlying `._averager` method. In addition to `.climatology` and `.departures`, we can extend `.average` and `.group_average` to support a `reference_period` keyword argument. 

Subsetting with `reference_period` makes sense for the climatological reference period. I'm thinking about whether there is enough value in adding subsetting directly in the other APIs, or if the user should subset _before_ calling them? 

1. Subset first with Xarray, then call xCDAT API
```
# This is basically the only line we need to add internally for xCDAT,
# besides validating the `reference_period` argument.
ds = ds.isel(time=slice("1850-01-01", "1899-01-01"))
ds.temporal.group_average("tas" freq="year")
```

2. Subset through xCDAT API:
```
ds.temporal.group_average("tas", freq="year", reference_period=("1850-01-01", "1899-01-01")
```

---

> @tomvothecoder Hope this updated [cookbook](https://github.com/xCDAT/xcdat_test/blob/67f2285312a84e0aeab381dbd51955729d925095/cookbook/seasonal_departure_from_baseline_clim.ipynb) to be helpful.

Thanks @lee1043! I'll take a look at the cookbook.

**Comment by chengzhuzhang** [comment]
@tomvothecoder hmmm, I guess the exact wording for the keyword `reference_period` fits for `.departures` only. If we were considering to add time selection for other APIs, it perhaps make more sense to use a more generic keyword argument  like `time_period` or `time_slice`. I guess it is easy enough for subset before calling xCDAT API, but option 2 seems good to have too, if we can have a clean implementation. I don't have a strong opinion on this...any preference @pochedls and @lee1043 ?

**Comment by lee1043** [comment]
@chengzhuzhang My vote is for having `reference_period` for `.departures` only. For the other operations like `climatology`, `average`, `group_average`, I think user can easily subset by using `.sel(time=slice("...", "..."))` and feed it to the function. For those operations calculation is one step, while departures has extra step that is "full time series" minus "climatology", where "climatology" could be defined in different time period than the "full time series". I think having `reference_period` for functions for the one-step operation could be confusing.

**Comment by pochedls** [comment]
`.departures` calls `.climatology` so it would be convenient if we also had an optional `reference_period` for  `.climatology`. This isn't that weird since we do often want climatologies over a certain period (e.g., the last 30 years). I think `reference_period` is an okay term for both, though they could be named differently (e.g., `reference_period` and `time_period` as @chengzhuzhang suggests). I also don't have strong opinions on this.

**Comment by pochedls** [comment]
Regarding the start / end of the time period. In thinking about how to implement this, I think by default we would just take the start/end of the month that the time point is in (e.g., `2023-01-01` or `2023-01-15` or `2023-01-31` would all map to the same bounds: [`2023-01-01 00:00:00`, `2023-02-01 00:00:00`]). This is easy to do, because a given time point, `t`, is stored as a cfTime object and you can directly retrieve the month / year (e.g., `t.month` would yield `1` in each case) and easily define the bounds from that information. 

I think the case where you would want to use `stored=1` is when the time point is stored at the end of the time period. For E3SM this would be `2023-02-01 00:00:00` (for January data) and calling `t.month` would give you `2` (and you don't want to set the start / end bounds to [`2023-02-01 00:00:00`, and `2023-02-28 00:00:00`]). So if E3SM didn't have time bounds, I think we'd want that `stored=1` value.

**Comment by chengzhuzhang** [comment]
> 



> `.departures` calls `.climatology` so it would be convenient if we also had an optional `reference_period` for `.climatology`. This isn't that weird since we do often want climatologies over a certain period (e.g., the last 30 years). I think `reference_period` is an okay term for both, though they could be named differently (e.g., `reference_period` and `time_period` as @chengzhuzhang suggests). I also don't have strong opinions on this.

Thank you for chiming in @lee1043, @pochedls ! 

After thinking about it more, using `reference_period` should be good, it perhaps will cause less confusion to use the same keyword.

**Comment by chengzhuzhang** [comment]
> Regarding the start / end of the time period. In thinking about how to implement this, I think by default we would just take the start/end of the month that the time point is in (e.g., `2023-01-01` or `2023-01-15` or `2023-01-31` would all map to the same bounds: [`2023-01-01 00:00:00`, `2023-02-01 00:00:00`]). This is easy to do, because a given time point, `t`, is stored as a cfTime object and you can directly retrieve the month / year (e.g., `t.month` would yield `1` in each case) and easily define the bounds from that information.
> 
> I think the case where you would want to use `stored=1` is when the time point is stored at the end of the time period. For E3SM this would be `2023-02-01 00:00:00` (for January data) and calling `t.month` would give you `2` (and you don't want to set the start / end bounds to [`2023-02-01 00:00:00`, and `2023-02-28 00:00:00`]). So if E3SM didn't have time bounds, I think we'd want that `stored=1` value.

@pochedls this makes good sense to me. Though I think this comment should belong to https://github.com/xCDAT/xcdat/issues/412?
