### ISSUE TITLE
[Doc]: temporal average no longer takes freq?

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#406]
### Describe your documentation update

In the example of temporal average [doc](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.temporal.average.html), 

```python
ds_month = ds.temporal.average("ts", freq="month")
ds_month.ts
```

But in my test with latest xcdat it returns
```
TypeError: TemporalAccessor.average() got an unexpected keyword argument 'freq'
```

I cannot recall we removed `freq` from temporal average, but if so, doc needs update accordingly.

**Comment by pochedls** [comment]
Good catch. Did you want [group_average()](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.temporal.group_average.html) or should `average` take `freq`? I've never used this function so I don't remember the history. 

The line that needs updating (to correct the documentation) is here: https://github.com/xCDAT/xcdat/blob/main/xcdat/temporal.py#L191.

**Comment by lee1043** [comment]
@pochedls Thanks for your comment. @pochedls @tomvothecoder please correct me if I am wrong, but I think we have separated `group_average` from `average`, so `group_average` can get annual cycle (12 time points if monthly) or seasonal mean (4 time points) or more, while `average` returns overall average (thus, one time point). In such case, I think it makes sense to not have `freq` option for `average`.

**Comment by tomvothecoder** [comment]
> @pochedls Thanks for your comment. @pochedls @tomvothecoder please correct me if I am wrong, but I think we have separated `group_average` from `average`, so `group_average` can get annual cycle (12 time points if monthly) or seasonal mean (4 time points) or more, while `average` returns overall average (thus, one time point). In such case, I think it makes sense to not have `freq` option for `average`.

Hey @lee1043, you are correct here. 

`.average()` collapses the time dimension. `freq` was removed from the method parameters and is instead inferred from the variable's time coordinates ([_infer_freq](https://github.com/xCDAT/xcdat/blob/c5db7b2ed7eff05655416e77b4a306aa7921b343/xcdat/temporal.py#L646-L672)).

We'll just need to update the `.average()` example to remove `freq`. Thanks!
