### ISSUE TITLE
[Doc]: xcdat API Reference not in (exact) alphabetical order

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#410]
### Describe your documentation update

I had a quick look at **bounds' related _stuff_** in the [xcdat documentation](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.bounds.get_bounds.html), after reading [this comment](https://github.com/xCDAT/xcdat/discussions/404#discussioncomment-4770047), and I used the `Previous` and `Next` buttons in the documentation.

I then noticed that the **entries in the API index far from being in alphabetical order** (see the out of place `regridder` in the `bounds` section, and other similar problems in the screenshot below). I don't know if this is a bug or a feature of _readthedocs_. Is there a way to fix this?

![xcdat_API_Reference_index](https://user-images.githubusercontent.com/2785573/214525922-a5a0150c-9f20-4af0-a835-2f96b984432f.png)

**Comment by tomvothecoder** [comment]
Thanks for pointing this out @jypeter! We'll take a look at this :)
