### ISSUE TITLE
[Bug]: xml open error

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#454]
### What happened?

I was opening a xml file that is indexed for multiple netcdf files. Opening as `open_mfdataset('*.nc')` worked but `open_mfdataset('test.xml')` returned error. 

Input data for the below minimal example code: [input.zip](https://github.com/xCDAT/xcdat/files/11315375/input.zip)

### What did you expect to happen?

I expected `open_mfdataset('*.nc')` and `open_mfdataset('test.xml')` result the same dataset.

### Minimal Complete Verifiable Example

```python
import xcdat as xc
ds = xc.open_mfdataset('precip.V1.0.1948.nc')
ds = xc.open_mfdataset('test_1948.xml')
```

### Relevant log output

Log from `ds = xc.open_mfdataset('precip.V1.0.1948.nc')`
```
2023-04-24 16:52:26,768 [WARNING]: dataset.py(decode_time:321) >> 'time' does not have a calendar attribute set. Defaulting to CF 'standard' calendar.
```

Log from `ds = xc.open_mfdataset('test_1948.xml')`
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[4], line 1
----> 1 ds = xc.open_mfdataset('test_1948.xml')

File ~/mambaforge/envs/xcdat_devel_20230419/lib/python3.10/site-packages/xcdat/dataset.py:233, in open_mfdataset(paths, data_var, add_bounds, bounds_axes, decode_times, center_times, lon_orient, data_vars, preprocess, **kwargs)
    229         paths = _parse_dir_for_nc_glob(paths)  # type: ignore
    231 preprocess = partial(_preprocess, decode_times=decode_times, callable=preprocess)
--> 233 ds = xr.open_mfdataset(
    234     paths,
    235     decode_times=False,
    236     data_vars=data_vars,
    237     preprocess=preprocess,
    238     **kwargs,  # type: ignore
    239 )
    241 ds = _postprocess_dataset(
    242     ds, data_var, center_times, add_bounds, bounds_axes, lon_orient
    243 )
    245 return ds

File ~/mambaforge/envs/xcdat_devel_20230419/lib/python3.10/site-packages/xarray/backends/api.py:948, in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
    945     paths = [os.fspath(p) if isinstance(p, os.PathLike) else p for p in paths]
    947 if not paths:
--> 948     raise OSError("no files to open")
    950 if combine == "nested":
    951     if isinstance(concat_dim, (str, DataArray)) or concat_dim is None:

OSError: no files to open
```

### Environment

xcdat 0.5.0

**Comment by pochedls** [comment]
I noticed that the feature to read xml files isn't documented in [open_mfdataset](https://github.com/xCDAT/xcdat/blob/main/xcdat/dataset.py#L137) – @tomvothecoder – should I add an issue to add this or should it be a hidden feature?

@lee1043 – this feature works by [reading the directory attribute from the cdml file](https://github.com/xCDAT/xcdat/blob/main/xcdat/dataset.py#L405) and then globbing the netcdf files in that directory. The xml file in your case has a blank directory attribute:

> grep directory test_1948.xml
> 	directory	=""

I think if you create the xml file with `cdscan -x test_1948.xml /absolute/path/to/data/*.nc` I think this should work.

I have other ideas to handle this case, but I think its probably best to try to populate the directory attribute in the cdml file.

**Comment by lee1043** [comment]
Hi @pochedls, thank you for your prompt reply. Yes, I was using the relative path, and it makes sense that the absolute path would work! I will test it.

**Comment by tomvothecoder** [comment]
> I noticed that the feature to read xml files isn't documented in [open_mfdataset](https://github.com/xCDAT/xcdat/blob/main/xcdat/dataset.py?rgh-link-date=2023-04-25T00%3A20%3A27Z#L137) – @tomvothecoder – should I add an issue to add this or should it be a hidden feature?
> 
> @lee1043 – this feature works by [reading the directory attribute from the cdml file](https://github.com/xCDAT/xcdat/blob/main/xcdat/dataset.py?rgh-link-date=2023-04-25T00%3A20%3A27Z#L405) and then globbing the netcdf files in that directory. The xml file in your case has a blank directory attribute:
> 
> `grep directory test_1948.xml`
> 
> > directory	=""
> 
> I think if you create the xml file with `cdscan -x test_1948.xml /absolute/path/to/data/*.nc` I think this should work.
> 
> I have other ideas to handle this case, but I think its probably best to try to populate the directory attribute in the cdml file.

We should update the `open_mfdataset` docstring using the docstrings from https://github.com/xCDAT/xcdat/blob/cbef082d9f3ea43aa7e4e36f4d2b23877a8826bc/xcdat/dataset.py#L402-L429

Another improvement is to make the error message more explicit. `OSError: no files to open` isn't really helpful. It should say something like `KeyError: This XML file does not have a 'directory' specifying an absolute direct path to *.nc dataset files`.

_On a side-note, we should limit the scope of XML support since CDML is being deprecated with CDAT. Ideally, this feature should be phased out in a future release and users should use glob paths directly instead._

**Comment by tomvothecoder** [comment]
> Another improvement is to make the error message more explicit. `OSError: no files to open` isn't really helpful. It should say something like `KeyError: This XML file does not have a 'directory' specifying an absolute direct path to *.nc dataset files`.

We should have a KeyError thrown with these lines:
https://github.com/xCDAT/xcdat/blob/cbef082d9f3ea43aa7e4e36f4d2b23877a8826bc/xcdat/dataset.py#L437-L441

We just need to figure out why it is not being thrown.

**Comment by lee1043** [comment]
> I think it is because `directory = ""` (which is not `None`).

I made the xml in the same directory where nc files are, and used relative path, e.g., `cdscan -x test.xml test*.nc`, which resulted `directory = ""`.  I will use absolute path to avoid this.

**Comment by lee1043** [comment]
I am closing this issue as the cause figured out. I think updating log message as @tomvothecoder suggested would be helpful. Or, maybe if `directory = ""`, then how about assume nc files are in the current directory?
