### ISSUE TITLE
[Doc]: update open_mfdataset documentation to include information on cdml/xml

### ISSUE THREAD

**Issue by pochedls** [xCDAT/xcdat#459]
### Describe your documentation update

From https://github.com/xCDAT/xcdat/issues/454, we realized that xcdat functionality to open cdml files is not included in the docstring for `open_mfdataset`. This should be done.

**Comment by pochedls** [comment]
As a bonus, we might be able to handle that issue with a simple if statement [here](https://github.com/xCDAT/xcdat/blob/cbef082d9f3ea43aa7e4e36f4d2b23877a8826bc/xcdat/dataset.py#L437-L441):

```
elif dir_attr == "":
    dir_attr = "."
```

**Comment by tomvothecoder** [comment]
Closed based on #503
