### ISSUE TITLE
[Doc]: Consider updating the listed APIs for horizontal regridding

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#501]
### Describe your documentation update

After revisiting the horizontal regridding APIs we have listed in the [API Reference](https://xcdat.readthedocs.io/en/stable/api.html) page, I think listing all of these options can be confusing for the user.

1. Python classes
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html
2. General accessor method 
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal.html
3. Individual accessor method by tool
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_xesmf.html
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_regrid2.html

All of these methods achieve the same functions, but go about it in a slightly different way. 
This is the callstack with `xesmf`: `horizontal(...tool="xesmf")` -> `horizonal_xesmf()` -> `XESMFRegridder()`.

### Solution
**I propose we just keep "2. General accessor method" listed in our documentation. I foresee most people using that API since it is the most straightforward to use and most flexible (you can specify `tool="regrid2"` or `tool="xesmf"`).**

**Comment by tomvothecoder** [comment]
Any thoughts @xCDAT/core-developers?

**Comment by pochedls** [comment]
I haven't investigated this enough to weigh in on what is right, but I do find the regridder documentation a little confusing (as mentioned [here](https://github.com/xCDAT/xcdat/issues/497#issuecomment-1581573962)). It seems like **2** has the correct documentation. 

One note regarding these references:

> Find options at [xcdat.regridder.xesmf.XESMFRegridder()](https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html#xcdat.regridder.xesmf.XESMFRegridder)

I think this is probably the best way to note/refer to options specific to xESMF / regrid2, but if there was a way of putting it within the documentation [here](https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal.html) that could be helpful.

**Comment by tomvothecoder** [comment]
> These are purely there for documentation, that's the only way to make a link to reference the individual regridder options.

You're right, I forgot you need to list the accessor class to list its methods and attributes.

> I'd be fine removing horizontal_xesmf and horizontal_regrid2, they really only save a single argument.

Yeah, I noticed people mostly using `horizontal()` in their code/notebooks. Those underlying APIs include `xesmf` or `regrid2` in the name of the method, which almost as many characters `tool='xesmf'`.

**Comment by jasonb5** [comment]
After some more thought we could solve the documentation issue by getting rid of `horizontal()` and `vertical()` and just have `regrid2()`, `xesmf()`, and `xgcm()`. We could group them together under `horizontal` and `vertical` in the documentation since users will probably learn about them there.

**Comment by jasonb5** [comment]
After the last meeting, the plan is to deprecate the current regridding accessor functions and remove them in a few release cycles.
- horizontal()
- vertical()

The `horizontal_xesmf()` and `horizontal_regrid2()` will remain and `vertical_xgcm()` will be added. Retaining the `horizontal` and `vertical` prefix will allow the possibility for a regridder to implement both vertical and horizontal.

The documentation will be moved to these methods so there will no longer be a link from the accessor methods to class `__init__` methods e.g. [accessor method](https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_xesmf.html) -> [class __init__](https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html#xcdat.regridder.xesmf.XESMFRegridder). Once this is done https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html and https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html can be removed. This will drastically clean up the regridding documentation and make the individual regridders documentation easier to access.

I will also do a pass on all the regridding documentation to update anything requiring clarification.

**Comment by jasonb5** [comment]
Closing as we've decided to stick with generic horizontal and vertical methods. PR https://github.com/xCDAT/xcdat/pull/535 addresses the documentation changes in this PR.
