### ISSUE TITLE
[Bug]: slow regrid2 operation 

### ISSUE THREAD

**Issue by lee1043** [xCDAT/xcdat#506]
### What happened?

When using `regridder.horizontal` I think its wall time is way longer than when do the same operation using cdat. 

### What did you expect to happen? Are there are possible answers you came across?

I wonder if we can make the `regrider.horizontal` operation faster.

### Minimal Complete Verifiable Example (MVCE)

```python
import cdms2
import cdutil
import xcdat as xc
import time

# CDAT
f = cdms2.open('navy_land.nc')
d = f('sftlf')
outgrid = cdms2.createUniformGrid(-90.0, 181, 1.0, 0.0, 360, 1.0)
start_time_cdat = time.time()
d_regrid = d.regrid(outgrid, regridTool='regrid2')
end_time_cdat = time.time()

# xCDAT
ds = xc.open_dataset('navy_land.nc', decode_times=False)
target_grid = xc.create_uniform_grid(-90, 90, 1.0, 0, 359, 1.0)
start_time_xcdat = time.time()
ds_regrid = ds.regridder.horizontal('sftlf', target_grid, tool='regrid2')
end_time_xcdat = time.time()

# wall time
print('cdat wall time:', end_time_cdat - start_time_cdat, "sec")
print('xcdat wall time:', end_time_xcdat - start_time_xcdat, "sec")
```

### Relevant log output

```python
cdat wall time: 0.26495885848999023 sec
xcdat wall time: 3.334275245666504 sec
```

### Anything else we need to know?

Input file: [navy_land.nc](https://github.com/CDAT/cdutil/blob/master/data/navy_land.nc)

The related Python modules:

- Public accessor method: https://github.com/xCDAT/xcdat/blob/c70827ac2378d1d2d947142a44206d8bd2a69662/xcdat/regridder/accessor.py#L163-L208
- Regrid2Regridder Class: https://github.com/xCDAT/xcdat/blob/c70827ac2378d1d2d947142a44206d8bd2a69662/xcdat/regridder/regrid2.py#L1-L547
- cdms2 regrid2 code (I think - Tom): https://github.com/CDAT/cdms/blob/master/regrid2/Lib/horizontal.py

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:19) 
[Clang 11.1.0 ]
python-bits: 64
OS: Darwin
OS-release: 22.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2023.5.0
pandas: 2.0.0
numpy: 1.21.3
scipy: 1.10.1
netCDF4: 1.6.0
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.2.0
distributed: 2023.2.0
matplotlib: 3.4.3
cartopy: 0.20.1
seaborn: 0.11.1
numbagg: None
fsspec: 2023.5.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.0
pip: 21.2.4
conda: None
pytest: 6.2.5
mypy: None
IPython: 8.14.0
sphinx: 6.1.3

**Comment by pochedls** [comment]
@lee1043 – Is xcdat loading the data into memory while you're timing it?

To check this, could you modify the xCDAT code to (note the `.load()` addition): 

```python
# xCDAT
ds = xc.open_dataset('navy_land.nc', decode_times=False).load()
target_grid = xc.create_uniform_grid(-90, 90, 1.0, 0, 359, 1.0)
start_time_xcdat = time.time()
ds_regrid = ds.regridder.horizontal('sftlf', target_grid, tool='regrid2')
end_time_xcdat = time.time()
```

You are loading CDAT before regridding. xCDAT will load on demand, so it is hard to tell if the difference in time is from the regridder or I/O.

**Comment by lee1043** [comment]
@pochedls thank you for your comment. It is still slow after `.load()` is added:

cdat wall time: 0.26210904121398926 sec
xcdat wall time: 2.924055814743042 sec

**Comment by tomvothecoder** [comment]
I updated the description to include links to the code in xCDAT for whoever wants to investigate or gets to it first.

**Comment by lee1043** [comment]
Thank you for the update. With #533, below is the wall clock time. xcdat used to take ~3.3s in my [previous test](https://github.com/xCDAT/xcdat/issues/506#issue-1757496069), which now takes ~1.9s. With adding `.load()`, time reduced from ~2.9s to ~1.6s. 

cdat wall time: 0.2637472152709961 sec
xcdat wall time: 1.9025719165802002 sec
xcdat wall time: 1.5795879364013672 sec (with `.load()`)
