### ISSUE TITLE
[Bug]: add_missing_bounds doesn't work for ERA5 data without X and Y axis

### ISSUE THREAD

**Issue by bosup** [xCDAT/xcdat#516]
### What happened?

```python
import xcdat as xc

ERA5_mask = "e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc"
ds_m = xc.open_mfdataset(ERA5_mask)
ds_m.latitude.attrs['standard_axis'] = 'Y'
ds_m.bounds.add_missing_bounds("Y")
```

```python
UFuncTypeError                            Traceback (most recent call last)
Cell In[67], line 5
      3 ds_m = xr.open_mfdataset(ERA5_mask)
      4 ds_m.latitude.attrs['standard_axis'] = 'Y'
----> 5 ds_m.bounds.add_missing_bounds("Y")

File ~/mambaforge/envs/M1/lib/python3.9/site-packages/xcdat/bounds.py:159, in BoundsAccessor.add_missing_bounds(self, width)
    156     pass
    158 try:
--> 159     bounds = self._create_bounds(axis, coord, width)
    160     ds[bounds.name] = bounds
    161     ds[coord.name].attrs["bounds"] = bounds.name

File ~/mambaforge/envs/M1/lib/python3.9/site-packages/xcdat/bounds.py:386, in BoundsAccessor._create_bounds(self, axis, coord_var, width)
    384     warnings.simplefilter("ignore", category=pd.errors.PerformanceWarning)
    385     # Get lower and upper bounds by using the width relative to nearest point.
--> 386     lower_bounds = coord_var - diffs[:-1] * width
    387     upper_bounds = coord_var + diffs[1:] * (1 - width)
    389 # Transpose both bound arrays into a 2D array.

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None
```

INPUT FILE: [e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc.zip](https://github.com/xCDAT/xcdat/files/11887214/e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc.zip)

### Environment

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:42:20) 
[Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.2
libnetcdf: 4.9.1

xarray: 2023.3.0
pandas: 1.5.3
numpy: 1.22.4
scipy: 1.10.1
netCDF4: 1.6.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.3.6
cfgrib: None
iris: None
bottleneck: None
dask: 2023.3.2
distributed: 2023.3.2.1
matplotlib: 3.7.1
cartopy: 0.21.1
seaborn: 0.12.2
numbagg: None
fsspec: 2023.4.0
cupy: None
pint: None
sparse: 0.14.0
flox: None
numpy_groupies: None
setuptools: 67.6.1
pip: 23.0.1
conda: None
pytest: None
mypy: None
IPython: 8.12.0
sphinx: None
```

**Comment by lee1043** [comment]
@bosup thank you for posting this. I edited your post little by applying formatting to make it more readable. 

For adding little bit more information, @bosup is opening ERA5 dataset and tried regridding, but it was not working, so he tried narrowing down the issue and found `add_missing_bounds` was not working as expected. Although this might be a data issue than xcdat issue, I thought it might be worth to take a look to understand where the issue comes from and if there is any easy way to prevent it. Any idea?

**Comment by lee1043** [comment]
@bosup I tested this code with the latest xcdat in the main branch and it does not return any error. Can you tell what is your xcdat version? You can see it by `conda list xcdat` in your terminal after activating your working conda environment. Can you also re-try this after updating your xcdat?

**Comment by tomvothecoder** [comment]
> Can you tell what is your xcdat version? 

Looks like v0.5.0 based on the traceback. In <=v0.5.0, time bounds were created using time coordinates as midpoints.
https://github.com/xCDAT/xcdat/blob/d0a48920e84af3a80375dad64918ac1c9b7a0097/xcdat/bounds.py#L384-L387

---

> I tested this code with the latest xcdat in the main branch and it does not return any error. 

In `main`, `add_missing_bounds()` now generates time bounds using the new `_create_time_bounds()` method (read docstring below). This might explain why this problem doesn't appear on `main` anymore.

`_create_time_bounds()`:
https://github.com/xCDAT/xcdat/blob/b46c331652ece58c13d00bb524a63f3aae750382/xcdat/bounds.py#L600-L612


**It would still be good to figure out why this dataset breaks when attempting to create time bounds using time coords as midpoints.**

**Comment by pochedls** [comment]
Is the syntax correct in the original issue/example? I think that in v5.0 you do not add the axis when calling [add_missing_bounds()](https://xcdat.readthedocs.io/en/v0.5.0/generated/xarray.Dataset.bounds.add_missing_bounds.html).

**Comment by bosup** [comment]
> @bosup I tested this code with the latest xcdat in the main branch and it does not return any error. Can you tell what is your xcdat version? You can see it by `conda list xcdat` in your terminal after activating your working conda environment. Can you also re-try this after updating your xcdat?

The version is 
# Name                    Version                   Build  Channel
xcdat                     0.5.0              pyhd8ed1ab_0    conda-forge

**Comment by bosup** [comment]
> Is the syntax correct in the original issue/example? I think that in v5.0 you do not add the axis when calling [add_missing_bounds()](https://xcdat.readthedocs.io/en/v0.5.0/generated/xarray.Dataset.bounds.add_missing_bounds.html).
> 
> @bosup – could you try this line: `ds_m.bounds.add_missing_bounds()`

thanks. it works after removing axis in ()

**Comment by lee1043** [comment]
> thanks. it works after removing axis in ()

That is great, thank you for keeping us updated, @bosup. 

I think we can close this issue unless @tomvothecoder wants to dig out deeper.

**Comment by tomvothecoder** [comment]
> Is the syntax correct in the original issue/example? I think that in v5.0 you do not add the axis when calling [add_missing_bounds()](https://xcdat.readthedocs.io/en/v0.5.0/generated/xarray.Dataset.bounds.add_missing_bounds.html).
> 
> @bosup – could you try this line: `ds_m.bounds.add_missing_bounds()`

@pochedls Thanks for finding this syntax error. I didn't look close enough to spot that. 

> It would still be good to figure out why this dataset breaks when attempting to create time bounds using time coords as midpoints.

After fixing syntax, the above is no longer happening. I'm closing this issue now.
