### ISSUE TITLE
[Doc]: Add a section about 'Updating xcdat'

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#544]
### Describe your documentation update

The documentation specifies (of course) [how to install xcdat](https://xcdat.readthedocs.io/en/stable/getting-started.html#installation), but adding a small section about (safely) **updating xcdat** (and its dependencies) would not hurt, especially for a _young_ package that you update regularly

I confess I'm never completely sure about the command I should use when updating a python package. `mamba update xcdat` worked this morning, but is it the same syntax with `conda` (i.e. `conda update xcdat`)?

**Comment by tomvothecoder** [comment]
Good idea. `mamba` is a drop-in replacement of `conda` (installed on top of `conda`). You can interchange the commands like this: `<mamba|conda> update xcdat`, although I go for `mamba` most of the time since it is much faster.
