### ISSUE TITLE
[Doc]: About the "xCDAT [...] HPC Machines" section

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#545]
### Describe your documentation update

The [xCDAT on Jupyter and HPC Machines](https://xcdat.readthedocs.io/en/stable/getting-started-hpc-jupyter.html) is useful

I think the part about **using a custom kernel** to an existing jupyter server (that the user already know how to use) should work

I'm less sure about **creating a new conda environment** on an HPC machine... This step involves downloading (a lot of) packages, which is usually impossible in the kind of secure environment you find on HPC machines

I don't really know what to suggest here. Maybe just _Ask you HPC support team to install xCDAT in an existing or a new Python environment_

And there is a **typo** in the following sentence: _you may need **top** open a new Notebook_

**Comment by jypeter** [comment]
Well, it does depend a lot on your account having a direct access to the outside world to download the required packages.

Our super-computing centers here don't offer that, but maybe they are more paranoid than others ;-)

**Comment by tomvothecoder** [comment]
> Well, it does depend a lot on your account having a direct access to the outside world to download the required packages.
> 
> Our super-computing centers here don't offer that, but maybe they are more paranoid than others ;-)

Thanks for the context. I'll think about adding some info that not all HPC environments might support user-managed conda installations and environments in bold.

> The conda installation instructions in this guide are based on the instructions provided by [NERSC](https://docs.nersc.gov/development/languages/python/nersc-python/). **However, setup can vary depending on the exact HPC environment you are working in so please consult your HPC documentation and/or HPC support resources. Some HPC environments might have security settings that restrict user-managed conda installations and environments.**
