### ISSUE TITLE
[Explore]: Interoperability between UXArray and xCDAT

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#551]
### Is your feature request related to a problem?

Notes from 9/13/23 meeting:

- Native E3SM, native CESM grid types
- UXArray decided on their API data models recently and how interoperable with Xarray ecosystem those models are 
  - Any functionality to get data models on grids that xCDAT can operate on?
- UXArray + xCDAT for time dimensional operations
- UXarray has no regridding functionality planned in near future, but Rob mentioned it is a good idea

Related discussion: https://github.com/xCDAT/xcdat/discussions/382

### Describe the solution you'd like
Objective: Convert UXArray objects into Xarray objects that are compatible with xCDAT functionalities (e.g., temporal averaging is a high priority)

- [x] Explore UXArray API structure
- [x] Gather requirements

**Comment by pochedls** [comment]
FYI: I think we would need something like this for inter-operability: https://github.com/UXARRAY/uxarray/discussions/46#discussioncomment-2746620

**Comment by tomvothecoder** [comment]
I'll start exploring UXARRAY in the next few weeks.

**Comment by chengzhuzhang** [comment]
Awesome, we might want to have UXArray also covered to some extent in the E3SM tutorial.

**Comment by tomvothecoder** [comment]
I'm using the [xcdat-validation](https://github.com/xCDAT/xcdat-validation/tree/main) for the uxarray exploration work. 

I merged a PR that includes an env with the latest stable version of xCDAT and Uxarray: https://github.com/xCDAT/xcdat-validation/blob/main/conda-env/test_uxarray.yml

There's also a new directory to store uxarray exploration material: https://github.com/xCDAT/xcdat-validation/tree/main/explore/uxarray

**Comment by tomvothecoder** [comment]
For spatial averaging, try pandas approach and then call APIs. @chengzhuzhang

**Comment by tomvothecoder** [comment]
A few things I've learned so far while working on the E3SM Tutorial Workshop practicum [notebook](https://github.com/xCDAT/xcdat-validation/blob/e3sm-workshop/demos/2024-e3sm-workshop/practicum_notebook.ipynb):

1. The `ux.UxDataset` and `ux.UxDataArray` classes just wrap the `xr.Dataset` and `xr.DataArray` classes, respectively. 
   - This means xCDAT can operate on `ux.UxDataset` and `ux.UxDataArray` objects natively. The dataset itself must have the correct CF metadata just like any other dataset.
2. `ux.open_dataset()` and `ux.open_mfdataset()` currently hard-codes `decode_times=False`, which cannot be overridden with `decode_times=True`. 
   - xCDAT temporal APIs require decoded times, which means xCDAT users must decode times manually downstream.
   - `xr.decode_cf(...decode_times=True, use_cftime=True)` can be used on the `ux.UxDataset` objects. **The main issue with this approach is that an `xr.Dataset` object is returned instead since this is an Xarray API. All of the `ux.UxDataset` attributes and operators will no longer be available on this returned `xr.Dataset`.**
   - This UXarray [PR](https://github.com/UXARRAY/uxarray/issues/766) removes the hard-coded `decode_times=False` and should be available in `uxarray=2024.04.01`
4. UXarray does not currently support unstructured to structured regridding.
   - Related [discussion](https://github.com/UXARRAY/uxarray/discussions/768)
   - xCDAT's spatial averager requires rectilinear grid. We will need to use `ncremap` for now.

**Comment by chengzhuzhang** [comment]
@tomvothecoder thank you for the notes! I'm curious when uxarray=2024.04.01 will become available. Maybe it will be in time for the unified release?

**Comment by tomvothecoder** [comment]
> @tomvothecoder thank you for the notes! I'm curious when uxarray=2024.04.01 will become available. Maybe it will be in time for the unified release?

No problem! I followed up with [here](https://github.com/UXARRAY/uxarray/issues/766#issuecomment-2070923616) Philip and asked when they typically release new versions. Hopefully the fix for decoding time will be available in time for E3SM Unified v1.10.0 on 4/29/24. If not, I can keep the warning about `decode_times` converting `ux.UxDataset` to `xr.Dataset` in the notebook.

**Comment by tomvothecoder** [comment]
> > @tomvothecoder thank you for the notes! I'm curious when uxarray=2024.04.01 will become available. Maybe it will be in time for the unified release?
> 
> No problem! I followed up with Philip [here](https://github.com/UXARRAY/uxarray/issues/766#issuecomment-2070923616) and asked when they typically release new versions. Hopefully the fix for decoding time will be available in time for E3SM Unified v1.10.0 on 4/29/24. If not, I can keep the warning about `decode_times` converting `ux.UxDataset` to `xr.Dataset` in the notebook.

Looks like uxarray=2024.04.01 will be released today (related [comment](https://github.com/UXARRAY/uxarray/issues/766#issuecomment-2071365559)), which means it should be available in time for E3SM Unified 1.10.0.

**Comment by tomvothecoder** [comment]
I think this is done based on my comment [above](https://github.com/xCDAT/xcdat/issues/551#issuecomment-2070867870) so I will close this issue. If anybody thinks otherwise, feel free to re-open and we can further explore UXarray.

**Comment by pochedls** [comment]
@tomvothecoder – I may be misunderstanding the scope of this issue, but I think we could leave this open. I think we could explore using kdtree or something (e.g., [here](https://github.com/xCDAT/xcdat/discussions/640#discussioncomment-9120497)) to do this.

**Comment by tomvothecoder** [comment]
I opened this [discussion item](https://github.com/xCDAT/xcdat/discussions/6571) for exploring Python-based unstructured to structured regridding solutions. This issue can be closed and we can consider this goal complete.

@xCDAT/core-developers
