### ISSUE TITLE
[Bug]: xc.swap_lon_axis returns UFuncBinaryResolutionError on standard xarray coordinates

### ISSUE THREAD

**Issue by bosup** [xCDAT/xcdat#554]
### What happened?

[lf_tag.nc.zip](https://github.com/xCDAT/xcdat/files/12854203/lf_tag.nc.zip)

when converting [0-360) longitude coordinates to [-180, 180), xc.swap_lon_axis method doesn't work on this data, please see attached data and relevant log output section 

`
import xarray as xr
import xcdat as xc
import numpy as np

ds = xr.open_mfdataset('lf_tag.nc')
lf_tag = ds.binary_tag

if np.max(lf_tag.lon) > 180:
    lf_tag = xc.swap_lon_axis(lf_tag, (-180, 180))
`

### Minimal Complete Verifiable Example (MVCE)

```python
import xarray as xr
import xcdat as xc
import numpy as np

ds = xr.open_mfdataset('lf_tag.nc')
lf_tag = ds.binary_tag

if np.max(lf_tag.lon) > 180:
    lf_tag = xc.swap_lon_axis(lf_tag, (-180, 180))
```

### Relevant log output

```python
ds = xc.swap_lon_axis(ds, (-180, 180))
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xcdat/axis.py", line 247, in swap_lon_axis
    new_coord = _swap_lon_axis(ds.coords[key], to)
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xcdat/axis.py", line 363, in _swap_lon_axis
    new_coords = ((coords + 180) % 360) - 180
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 240, in __mod__
    return self._binary_op(other, operator.mod)
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xarray/core/dataarray.py", line 4620, in _binary_op
    f(self.variable, other_variable)
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 446, in __mod__
    return self._binary_op(other, operator.mod)
  File "/global/homes/d/dong12/miniconda3/envs/PMP/lib/python3.10/site-packages/xarray/core/variable.py", line 2705, in _binary_op
    f(self_data, other_data) if not reflexive else f(other_data, self_data)
numpy.core._exceptions._UFuncBinaryResolutionError: ufunc 'remainder' cannot use operands with types dtype('<M8[ns]') and dtype('int64')
```

### Anything else we need to know?

dimensions:
	lat = 721 ;
	lon = 1440 ;
variables:
	int time ;
		time:long_name = "time" ;
		time:units = "hours since 1900-01-01" ;
		time:calendar = "gregorian" ;
	double lat(lat) ;
		lat:_FillValue = NaN ;
		lat:long_name = "latitude" ;
		lat:short_name = "lat" ;
		lat:units = "degrees_north" ;
		lat:qualifier = "Gaussian" ;
	double lon(lon) ;
		lon:_FillValue = NaN ;
		lon:long_name = "longitude" ;
		lon:short_name = "lon" ;
		lon:units = "degrees_east" ;
	float binary_tag(lat, lon) ;
		binary_tag:_FillValue = NaNf ;
		binary_tag:coordinates = "time" ;

dask.array<where, shape=(721, 1440), dtype=float32, chunksize=(721, 1440), chunktype=numpy.ndarray>
Coordinates:
    time     datetime64[ns] 1979-01-01
  * lat      (lat) float64 90.0 89.75 89.5 89.25 ... -89.25 -89.5 -89.75 -90.0
  * lon      (lon) float64 0.0 0.25 0.5 0.75 1.0 ... 359.0 359.2 359.5 359.8

### Environment

xCDAT version 0.5.0

commit: None
python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
python-bits: 64
OS: Linux
OS-release: 5.14.21-150400.24.81_12.0.86-cray_shasta_c
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.1
libnetcdf: 4.9.2

xarray: 2023.7.0
pandas: 2.0.3
numpy: 1.22.4
scipy: 1.11.1
netCDF4: 1.6.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.2
nc_time_axis: None
PseudoNetCDF: None
iris: None
bottleneck: None
dask: 2023.7.1
distributed: 2023.7.1
matplotlib: 3.7.2
cartopy: 0.21.1
seaborn: 0.12.2
numbagg: None
fsspec: 2023.6.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 68.0.0
pip: 23.2.1
conda: None
pytest: None
mypy: None
IPython: 8.14.0
sphinx: None
None

**Comment by pochedls** [comment]
@bosup – it seems like you are passing an `xr.DataArray` into `xc.swap_lon_axis`, but I think it takes an `xr.Dataset` (see [here](https://xcdat.readthedocs.io/en/stable/generated/xcdat.swap_lon_axis.html)). 

Could you try something like:

```python
if np.max(lf_tag.lon) > 180:
    lf_tag = xc.swap_lon_axis(ds, (-180, 180))['lf_tag']
```

**Comment by bosup** [comment]
@pochedls Thanks!
I tried swap_lon_axis on xr.Dataset but it still doesn't work
the dataset is like
```
![image](https://github.com/xCDAT/xcdat/assets/130708142/f5af3def-1878-43dd-aac3-a19d27cb0a7c)
```
it looks like the time dimension is empty. I tried to drop the time dimension using Dataset.squeeze('time') but there are some errors 
```
File ~/mambaforge/envs/M1/lib/python3.9/site-packages/xarray/core/utils.py:455, in Frozen.__getitem__(self, key)
    454 def __getitem__(self, key: K) -> V:
--> 455     return self.mapping[key]
KeyError: 'time'
```

**Comment by pochedls** [comment]
I think if you use `ds = ds.drop_vars('time')` and then swap the axes it should work.

**Comment by bosup** [comment]
@pochedls Thanks! it works

**Comment by lee1043** [comment]
@pochedls Thank you for stepping in and help @bosup. 

@bosup I consider this as a data issue rather than xcdat. With that I am closing this issue, but please feel free to reopen it if you would need.
