### ISSUE TITLE
[Bug]: Can't update to 0.6.0 with "mamba update xcdat" and Python 3.8

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#557]
### What happened?

I have tried to update from 0.5.0 to 0.6.0, following the [Updating](https://xcdat.readthedocs.io/en/stable/getting-started.html#updating) instructions, but nothing happens

And I get an error I'm not familiar with if I explicitly request 0.6.0

```
 >conda list | grep xcdat

xcdat                     0.5.0              pyhd8ed1ab_0    conda-forge

 >mamba update xcdat

[...]
Looking for: ['xcdat']

conda-forge/linux-64                                          No change
conda-forge/noarch                                            No change
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change

Pinned packages:
  - python 3.8.*


Transaction

  Prefix: /home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm_py3

  All requested packages already installed

 >mamba update xcdat=0.6.0
[...]
Looking for: ['xcdat=0.6.0']

[...]

Pinned packages:
  - python 3.8.*


Encountered problems while solving:
  - nothing provides _python_rc needed by python-3.12.0rc3-rc3_hab00c5b_1_cpython
```

### What did you expect to happen? Are there are possible answers you came across?

I expected to get the new 0.6.0 version, or some error message about dependencies

Is there a problem due to the fact that my environment is based on python 3.8 ?

### Environment

```
 >conda list | grep xcdat

xcdat                     0.5.0              pyhd8ed1ab_0    conda-forge
```

```
>>> xr.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.80.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 2022.9.0
pandas: 1.2.3
numpy: 1.21.4
scipy: 1.7.0
netCDF4: 1.5.6
pydap: None
h5netcdf: 0.13.1
h5py: 2.10.0
Nio: None
zarr: 2.11.0
cftime: 1.6.2
nc_time_axis: 1.4.1
PseudoNetCDF: None
rasterio: None
cfgrib: 0.9.9.0
iris: 3.1.0
bottleneck: 1.3.7
dask: 2021.02.0
distributed: 2021.02.0
matplotlib: 3.3.4
cartopy: 0.18.0
seaborn: 0.11.1
numbagg: None
fsspec: 0.8.7
cupy: None
pint: 0.20.1
sparse: 0.13.0
flox: 0.7.2
numpy_groupies: 0.9.22
setuptools: 49.6.0.post20210108
pip: 22.0.4
conda: None
pytest: 6.2.4
IPython: 7.21.0
sphinx: 3.5.2
```

**Comment by jypeter** [comment]
I'd rather not touch the Python in my multi-user/packages environment !

I will try to move forward "creating a new shared environment based on the latest Python"

**Comment by tomvothecoder** [comment]
Hey @jypeter, did you ever figure this out?

**Comment by jypeter** [comment]
Nope. I have not created a new environment (that is, based on a more recent version of conda and python). It may take a while

But you were probably right that my python is too old to handle 0.6.0. You can close this issue if you want

**Comment by lee1043** [comment]
I found using python 3.8 therefore having xarray version limited to 2022.11.0 can cause issue when dealing time, because of some changes made in pandas. Newer versions of xarray were correctly patched for the pandas change. So it might be worth consider using python 3.9 or above.

More details on the issue I had can be found here:
https://github.com/xCDAT/xcdat/issues/560#issuecomment-1773995886

**Comment by tomvothecoder** [comment]
> Nope. I have not created a new environment (that is, based on a more recent version of conda and python). It may take a while
> 
> But you were probably right that my python is too old to handle 0.6.0. You can close this issue if you want

Thanks, just making sure. I'll go ahead and close it.
