### ISSUE TITLE
[Deprecation]: Deprecate CDML support in `open_dataset()` and `open_mfdataset()`

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#604]
We've had this info in our docstrings but not as a GitHub issue. Support for CDAT has ceased in Dec. 2023, including `cdscan` which produces CDML (XML) files.

Related lines of code:

- https://github.com/xCDAT/xcdat/blob/94271f151b182c6b8dd4cb726df1dcc2658e2b4d/xcdat/dataset.py#L167-L175
- https://github.com/xCDAT/xcdat/blob/94271f151b182c6b8dd4cb726df1dcc2658e2b4d/xcdat/dataset.py#L267-L273
- [_is_xml_filepath](https://github.com/xCDAT/xcdat/blob/94271f151b182c6b8dd4cb726df1dcc2658e2b4d/xcdat/dataset.py#L431-L446)
- [_parse_xml_for_nc_glob](https://github.com/xCDAT/xcdat/blob/94271f151b182c6b8dd4cb726df1dcc2658e2b4d/xcdat/dataset.py#L449-L480)

**Comment by tomvothecoder** [comment]
Hey @lee1043, are still using xCDAT’s CDML support in `open_mfdataset()` in the PCMDI Metrics? Or did you go back to using the PCMDI Metrics CDML function, before CDML support was added to xCDAT?

I'm aware you're still converting PCMDI Metrics to use Xarray/xCDAT and would like to gauge what a good time is to deprecate this feature in xCDAT.

**Comment by lee1043** [comment]
@tomvothecoder thank you for checking. I am using xml files but via a [function](https://github.com/PCMDI/pcmdi_metrics/blob/09140cf98a16ae57790e03b895c7f14298c24756/pcmdi_metrics/io/xcdat_openxml.py#L11) embedded in PMP. I am okay with the deprecation in xCDAT.
