### ISSUE TITLE
BUG: Incorrect DOI Reference in Paper Draft

### ISSUE THREAD

**Issue by mgrover1** [xCDAT/xcdat#621]
### What happened?

One of the DOI links is improperly formatted in the paper draft - https://github.com/xCDAT/xcdat/blob/f995ec6716a69d2613b08dcd3e5de0bed20ba122/docs/paper/paper.bib#L79

This is related to the review
https://github.com/openjournals/joss-reviews/issues/6426

### What did you expect to happen? Are there are possible answers you came across?

This should just be the DOI ID portion (10.1029/2022MS003156), but instead includes the URL as well. Removing the prefix should fix this.

### Environment

N/A

**Comment by mgrover1** [comment]
@tomvothecoder - looks like this commit resolves the issue
https://github.com/xCDAT/xcdat/pull/567/commits/0d5a98131e8f06f7e0339d0c846ece6856b410f6

I think we can close this, as this issue refers to the PR not necessarily the main branch?

**Comment by tomvothecoder** [comment]
Sounds good! Thanks @mgrover1
