### ISSUE TITLE
[Doc]: update xcdat Regridding doc and link to/from xESMF

### ISSUE THREAD

**Issue by jypeter** [xCDAT/xcdat#639]
### xESMF website

I have just noticed that there is an old link from the xESMF [Other geospatial regridding tools](https://xesmf.readthedocs.io/en/stable/other_tools.html) page to [Regridder in UV-CDAT](https://uvcdat.llnl.gov/documentation/cdms/cdms_4.html). You may want to ask them to link to the xCDAT home page, or to your [Horizontal Regridding](https://xcdat.readthedocs.io/en/latest/examples/regridding-horizontal.html) page

### xCDAT Horizontal Regridding

- xCDAT [Horizontal Regridding](https://xcdat.readthedocs.io/en/latest/examples/regridding-horizontal.html) page mentions xESMF at the beginning of the page, but you have to scroll down to sections 4 and 5 to find actual links to the the xESMF documentation. Maybe you could (also) have a link to the [xESMF: Universal Regridder for Geospatial Data](https://xesmf.readthedocs.io/en/stable/) website closer to the top

 - the links you use for xESMF (including your [xarray.Dataset.regridder.horizontal](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.regridder.horizontal.html) page) use https://pangeo-xesmf.readthedocs.io/en/latest/, but I have seen that the same documentation is also available at https://xesmf.readthedocs.io/en/stable/. Both links seem to have the same content, but the one without `pangeo-` may be more _canonical_?

**Comment by tomvothecoder** [comment]
Thanks for opening this GitHub issue, @jypeter. Pull requests are always welcome!
