### ISSUE TITLE
[Doc]: Double check plot in vertical regridding notebook

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#649]
### Describe your documentation update

@lee1043 mentioned in a meeting that a plot in the vertical regridding notebook doesn't look right, specifically the lat/lon axis.

We should double-check to make sure it is correct.

https://xcdat.readthedocs.io/en/stable/examples/regridding-vertical.html#3.-Remapping-air-temperature-on-pressure-levels-to-a-set-of-target-pressure-levels.

**Comment by lee1043** [comment]
@tomvothecoder thanks for opening the issue but I should withdraw the comment because that was resulted from my confusion.
