### ISSUE TITLE
[Bug]: `VersionMismatch` exception with `esmf=8.4.2` and `esmpy=8.6.0` for an E3SM Unified 1.10.0 user 

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#654]
### What happened?

An attendee at the E3SM tutorial workshop ran into a `VersionMismatch` error with `esmf=8.4.2` and `esmpy=8.6.0` after running the `import` cell containing `xcdat` ([source notebook](https://github.com/xCDAT/xcdat-validation/blob/main/demos/2024-e3sm-workshop/xcdat_practicum_notebook.ipynb)).

This notebook requires the user to setup and activate the E3SM Unified v1.10.0 kernel. I was unable to reproduce this issue on my end.

### What did you expect to happen? Are there are possible answers you came across?

The user should have been able to use the E3SM Unified 1.10.0 kernel. Other attendees running the xCDAT notebook did not run into this issue.

I'm not sure exactly the root cause of this issue because the environment is pre-built with all of the required dependencies.

### Anything else we need to know?

- Attendee was using the [NERSC Jupyter Hub](https://jupyter.nersc.gov/hub/login?next=%2Fhub%2Fhome) like everyone else. They were also on an M1 Mac, which shouldn't matter since they were using the NERSC Jupyter Hub.

### Environment

E3SM Unified v1.10.0
xCDAT=0.7.0

**Comment by tomvothecoder** [comment]
This issue seemed to only affect that single user. I will close for now.

**Comment by pochedls** [comment]
I have also hit this issue, but I figured out some way around it (I don't remember the details).

**Comment by tomvothecoder** [comment]
> I have also hit this issue, but I figured out some way around it (I don't remember the details).

This might have occurred in older versions of xCDAT. I don't think it should be happening in the more recent versions with esmpy/esmf/xesmf constraints.
