### ISSUE TITLE
KeyError: 'bnds' when trying to compute spatial average

### ISSUE THREAD

**Issue by mzelinka** [xCDAT/xcdat#685]
I am hitting an error that I don't understand.  If I try to do the following:
`DS = xc.open_dataset('/p/user_pub/climate_work/zelinka1/xclim/CMIP6.ACCESS-CM2.r1i1p1f1.clt.annualxsmaps.nc',decode_times=False)`

`avg=DS.spatial.average('clt')`

I get the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[105], line 4
      2 # DS = DS.assign_coords(exp=("exp",['ssp126', 'ssp245', 'ssp370', 'ssp585']))
      3 DS
----> 4 avg=DS.spatial.average('clt')

File [~/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py:195](http://127.0.0.1:8082/lab/tree/scripts/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py#line=194), in SpatialAccessor.average(self, data_var, axis, weights, keep_weights, lat_bounds, lon_bounds)
    192 elif isinstance(weights, xr.DataArray):
    193     self._weights = weights
--> 195 self._validate_weights(dv, axis)
    196 ds[dv.name] = self._averager(dv, axis)
    198 if keep_weights:

File [~/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py:693](http://127.0.0.1:8082/lab/tree/scripts/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py#line=692), in SpatialAccessor._validate_weights(self, data_var, axis)
    687         raise KeyError(
    688             f"The weights DataArray does not include an {key} axis, or the "
    689             "dimension names are not the same."
    690         )
    692 # Check the weight dim sizes equal data var dim sizes.
--> 693 dim_sizes = {key: data_var.sizes[key] for key in self._weights.sizes.keys()}
    694 for dim, size in self._weights.sizes.items():
    695     if size != dim_sizes[dim]:

File [~/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py:693](http://127.0.0.1:8082/lab/tree/scripts/miniconda3/envs/xclim2/lib/python3.10/site-packages/xcdat/spatial.py#line=692), in <dictcomp>(.0)
    687         raise KeyError(
    688             f"The weights DataArray does not include an {key} axis, or the "
    689             "dimension names are not the same."
    690         )
    692 # Check the weight dim sizes equal data var dim sizes.
--> 693 dim_sizes = {key: data_var.sizes[key] for key in self._weights.sizes.keys()}
    694 for dim, size in self._weights.sizes.items():
    695     if size != dim_sizes[dim]:

File [~/miniconda3/envs/xclim2/lib/python3.10/site-packages/xarray/core/utils.py:427](http://127.0.0.1:8082/lab/tree/scripts/miniconda3/envs/xclim2/lib/python3.10/site-packages/xarray/core/utils.py#line=426), in Frozen.__getitem__(self, key)
    426 def __getitem__(self, key: K) -> V:
--> 427     return self.mapping[key]

KeyError: 'bnds'
```

I can't see what is wrong with this dataset that is triggering this error, since I can perform this operation on other datasets that look essentially identical.

**Comment by pochedls** [comment]
In this dataset, the `lat_bnds` and `lon_bnds` are somewhat atypical/complicated and vary by experiment, time, lat, and lon (xcdat currently only works for static bounds, e.g., `lat_bnds(lat)`): 

`ds.lat_bnds`
> <xarray.DataArray 'lat_bnds' (exp: 4, time: 251, lat: 90, bnds: 2)> Size: 1MB

I suspect that your bounds actually are static, but this isn't reflected in the dataset because of how the original files were opened / saved:

`ds.lat_bnds.values[0, 0] - ds.lat_bnds.values[2, 10]`:

> array([[0., 0.],
>        [0., 0.],
>        [0., 0.],
> ...

One simple fix you could consider is to regenerate the bounds (please verify the re-generated bounds are the same as the original bounds):

```
ds = ds.drop_vars(['lat_bnds', 'lon_bnds'])
ds = ds.bounds.add_missing_bounds(['X', 'Y'])
dsa = ds.spatial.average('clt')
```

You may also be able to do something like this:

```
ds['lat_bnds'] = ds.lat_bnds.isel(time=0, exp=0)
ds['lon_bnds'] = ds.lon_bnds.isel(time=0, exp=0)
dsa = ds.spatial.average('clt')
```

**Comment by mzelinka** [comment]
Thank you, that works. The dataset in this file was originally generated by concatenating 4 datasets (one for each of the ssp experiments). I guess concatenating datasets can lead to apparently non-static lat_bnds and lon_bnds on the resulting combined dataset.

**Comment by pochedls** [comment]
I am not sure what exactly happened, but bound dims can be sensitive to arguments like `data_vars` and `coords` in xarray/xcdat `open_mfdataset`. xcdat uses `data_vars=minimal` by default. xarray uses `all`, which can sometimes contribute to this kind of behavior (though I don't know if that is what happened in this case).

**Comment by pochedls** [comment]
This issue can be resolved with this workaround, but could be re-visited if there was a feature request to handle this kind of behavior.
