### ISSUE TITLE
Move repository to parent project org and add license

### ISSUE THREAD

**Issue by tomvothecoder** [XCDAT/xcdat#69]
Once the project is officially funded, we should move the repo to the parent project org and add a license.

Acceptance Criteria
- [x] Move to XCDAT organization
- Update repo links
   - [x] `README.rst`
   - [x] `CONTRIBUTING.RST`
   - [x] `docs/index.rst`
   - [x] `docs/getting_started.rst`
   - [x] `docs/project_maintenance.rst`
   - [x] `setup.py`
   - [x] `tbump.toml`
   - [x] `conda-recipe/meta.yaml`
- [x] Rename xCDAT to XCDAT

**Comment by pochedls** [comment]
Or possibly PCMDI, depending on funding...
