### ISSUE TITLE
[Enhancement]: Consider how to test for correct weights generation in xCDAT

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#699]
### Is your feature request related to a problem?

In PR #689, in the `TemporalAccessor._get_weights()` method, I removed validation that checks the sums of weights for each time group adds up to 1 (related [code](https://github.com/xCDAT/xcdat/blob/584fccee91f559089e4bb24c9cc45983b998bf4a/xcdat/temporal.py#L1296-L1299)).

This was done because:
1. Assertion code should only be used in testing and debugging ([link](https://snyk.io/blog/the-dangers-of-assert-in-python/)) -- TLDR: They can be turned off by the user (`-O` flag), not good practice. I copied this validation code from an Xarray notebook ([link](https://docs.xarray.dev/en/stable/examples/monthly-means.html#Now-for-the-heavy-lifting:)) without realizing the implications.
2. I added unit tests to cover the implementation logic using the same validation code ([here](https://github.com/xCDAT/xcdat/blob/e9e73dd98e20b77e690fd3b4cf6df947a9f58e60/tests/test_temporal.py#L2220-L2237))
3. `np.testing.assert_allclose()` degrades performance -- I expect the performance degradation to scale up in relation to the size to the data, maybe it loads data into memory with `.values`?

### What is an assertion and when to use it
> `assert` is a common idiom in many languages. The purpose is to check conditions that are expected to always be true. A failed assertion indicates a coding bug. Therefore, the method returns nothing normally, and throws an exception if the condition fails.
> ...
> Assertions are supposed to pass 100% of the time. An exception is only thrown when the condition unexpectedly fails.
>
> -- <cite> https://stackoverflow.com/questions/42837054/are-assert-methods-acceptable-in-production</cite>

### Option 1: Don't keep this assertion

I think the sum of weights for each group should always be 1.0 (100%) based on our implementation logic. Otherwise, the assertion would indicate a coding error on our behalf rather than bad data (although we can raise an exception if it is indeed actually due to bad time bounds). As far as I can tell, our implementation logic is right and nobody has ran into `_get_weights()` throwing an `AssertionError` from the validation code. 

The `_get_weights()` method works by:

1. Get time lengths by taking the difference between bounds (`time_lengths`)
2. Group time lengths (`grouped_time_lengths`)
3. Divide grouped time lengths by the sum of each group (`grouped_time_length / grouped_time_lengths.sum()`) 

https://github.com/xCDAT/xcdat/blob/e9e73dd98e20b77e690fd3b4cf6df947a9f58e60/xcdat/temporal.py#L1213-L1262

### Option 2: Keep this assertion

Maybe the time bounds might not be correct for some reason and it produces incorrect weight for certain groups (e.g., missing data)? Not sure here. I will try experimenting with bad time bounds.

#### If we want to keep this assertion:
1. Figure out how to safely use `np.testing.assert_allclose()` in production since it raises an `AssertionError` that can be turned off by the user
2. Find a way to optimize performance for `np.testing.assert_allclose()`
3. Raise a `RuntimeError` if numpy assertion error is raised

### Additional context

After this ticket is addressed, we can proceed with releasing v0.7.2.

**Comment by tomvothecoder** [comment]
@xCDAT/core-developers Any input would be appreciated here. Thanks.

**Comment by pochedls** [comment]
I think you can go with option 1 (drop the assertion). Even though I raised concern about removing this, when I review this code carefully, I don't think it is needed. Do you remember why it was put there in the first place?

I don't think I helped write this section of code, but I sometimes add these kind of tests to make sure NaNs aren't messing things up. I don't think that should be an issue in this instance.

**Comment by tomvothecoder** [comment]
> Do you remember why it was put there in the first place?

I based my initial implementation of `_get_weights()` on the Xarray notebook [here](https://docs.xarray.dev/en/stable/examples/monthly-means.html#Now-for-the-heavy-lifting:), which includes that validation code. It was good to have while implementing the logic in xCDAT, but I don't think it is necessary in production.

**Comment by tomvothecoder** [comment]
I ran all of the grouping-based temporal averaging APIs with a dummy dataset that has bad bounds. They all worked and did not throw an AssertionError.

Weights should always correctly add up to 1.0 for each group based on how the [_group_data()](https://github.com/xCDAT/xcdat/blob/e9e73dd98e20b77e690fd3b4cf6df947a9f58e60/xcdat/temporal.py#L1264-L1288) method works. This method labels each time coordinate with a group. The time bounds are used to calculate the weight for each specific coordinate. If we sum up weights for each group, they should still add up to 1.0. If there are bad time coordinates (e.g., one very off time coordinate), it will be its own group with a sum weight of 1.0. This is a data quality issue that the user should address beforehand.

```python
# %%
import numpy as np
import pandas as pd
import xarray as xr
import xcdat as xc

# Define a time range with valid dates
times = pd.date_range(start="2000-01-01", periods=30, freq="ME")


# %%
# Create time bounds (lower and upper values)
time_bnds = np.array([times[:-1], times[1:]]).T
time_bnds = np.concatenate(
    (
        time_bnds,
        np.array([[times[-1], pd.Timestamp("2010-12-31")]], dtype="datetime64[ns]"),
    )
)
# Introduce incorrect time bounds
time_bnds[4, 1] = pd.Timestamp("3000-01-01")
time_bnds[8, 0] = pd.Timestamp("3000-01-01")


# %%
# Create some dummy data
data = np.random.rand(len(times))

# Create a dataset with these time coordinates and time bounds
ds = xr.Dataset(
    {"data": (["time"], data)},
    coords={"time": times, "time_bnds": (["time", "bnds"], time_bnds)},
)


# Add CF attributes
ds.attrs = {
    "Conventions": "CF-1.8",
    "title": "Sample Dataset",
    "institution": "Your Institution",
    "source": "Synthetic data",
    "history": "Created for demonstration purposes",
    "references": "http://example.com",
}

ds["data"].attrs = {
    "long_name": "Random Data",
    "units": "1",
    "standard_name": "random_data",
}

ds["time"].attrs = {
    "long_name": "Time",
    "standard_name": "time",
    "axis": "T",
    "bounds": "time_bnds",
}

ds["time_bnds"].attrs = {
    "long_name": "Time Bounds",
    "standard_name": "time_bnds",
}


# %%
ds_day = ds.temporal.group_average("data", freq="day")
ds_month = ds.temporal.group_average("data", freq="month")
ds_month = ds.temporal.group_average("data", freq="season")
ds_year = ds.temporal.group_average("data", freq="year")

# %%
ds_climo_day = ds.temporal.climatology("data", freq="day")
ds_climo_month = ds.temporal.climatology("data", freq="month")
ds_climo_season = ds.temporal.climatology("data", freq="season")

# %%
ds_depart_day = ds.temporal.departures("data", freq="day")
ds_depart_month = ds.temporal.departures("data", freq="month")
ds_depart_season = ds.temporal.departures("data", freq="season")


```

**Comment by tomvothecoder** [comment]
Closing this issue based on my findings.
